### ISSUE TITLE
Change Language for User Interface of SS admin

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#1000]
Dear @petkivim!

I want to change language for user interface on https://IP-SS:4000. Have you got document for this?, Can you give me this document?.

Best Regard!

**Comment by petkivim** [comment]
Hi @trungnv0412 

Unfortunately, there's no documentation available on changing the UI language. If you want to support multiple languages in the UI, you should implement a language switcher component and add translations for the new language. The locales are located here:

https://github.com/nordic-institute/X-Road/tree/develop/src/proxy-ui-api/frontend/src/locales

Regards,
Petteri

**Comment by trungnv0412** [comment]
Thank for your support

Best Regard!
