### ISSUE TITLE
SSL authentication failed Client has no IS certificates

### ISSUE THREAD

**Issue by jmhal** [nordic-institute/X-Road#1002]
Hello X-Road Community, 

I am following this [tutorial](https://confluence.niis.org/pages/viewpage.action?pageId=6783483) on how to configure a Central Server. Everything seems OK, until the final step, "4.3 Register the subsystem". From my understanding, in this section we are adding a subsystem in the Central Server for later registration on the Security Server. I was able to add the TEST subsystem to the Central Server (subsection 4.1). But things started looking different in subsection 4.2, in the Security Server. First, when I try to add the client, the search does not find the TEST subsystem. I place the information by hand and I try to register it the following message appears:

>  SSL authentication failed
Client 'SUBSYSTEM:DEV/GOV/1234/MANAGEMENT' has no IS certificates
ID: d8ccaf4ed326a664 

I tried to disable HTTPS for HTTP on the MANAGEMENT subsystem internal servers but still get the same message. Should I really upload a certificate? If so, any one would do? Should it be signed by TESTCA?

Any thoughts?

**Comment by petkivim** [comment]
Hi @jmhal 

The reason for the error message is that the `Verify TLS certificate` option is selected in the management services' configuration. Unchecking the option should resolve the problem. After changing the configuration it will take around a minute before the new value is effective.

![Screenshot 2021-07-08 at 8 03 05](https://user-images.githubusercontent.com/575897/124865423-50ac0680-dfc3-11eb-8734-723cf1699b78.png)

When the `Verify TLS certificate` option is selected the lock icons are green. After unchecking the `Verify TLS certificate` option is selected they will become yellow:

![Screenshot 2021-07-08 at 8 02 52](https://user-images.githubusercontent.com/575897/124865401-44c04480-dfc3-11eb-8e56-7a41a6a410b8.png)

In case you wish to verify the TLS certificate, you have to copy the certificate from the Central Server ([how to find it](https://confluence.niis.org/pages/viewpage.action?pageId=40665199)) and upload it to the management Security Server:

![Screenshot 2021-07-08 at 8 16 30](https://user-images.githubusercontent.com/575897/124866295-d8464500-dfc4-11eb-9081-88337da19c9c.png)

Regards,
Petteri

**Comment by jmhal** [comment]
Hello @petkivim ,

Thank you very much again. I believe that I misunderstood the flow of request. I thought that just disabling HTTPS for internal servers would suffice. I did as you detailed, retrieving the Central Server certificate and add it up to the Management Services. After that, everything works like a charm.

I will work my way through installing another Security Server now.

Regards.
