### ISSUE TITLE
No valid Certificate when Registering the Auth Cetificate

### ISSUE THREAD

**Issue by VirajAttanayake** [nordic-institute/X-Road#1047]
I have install the Docker version of Central Server and Security Server.  I get below error when I register the Auth Key from Security server.

![image](https://user-images.githubusercontent.com/16677999/133828588-2d27dcf4-7aca-4f41-af59-6cadfdb8af34.png)

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

There are currently two problems. First, the authentication certificate is disabled - you have to activate in the certificate details before sending the registration request. Second, the OCSP status of the the sign certificate is `Unknown`. Sending the authentication certificate registration request requires that the sign cert OCSP status is `Good`. Have you checked that the Security Server is able to connect to the OCSP service?

Regards,
Petteri

**Comment by VirajAttanayake** [comment]
Hi Petteri,

Yes I forgot to activate the Auth certificate.  The Security Server Docker and Central Server Docker runs on two VM's. So the Security server is not possible to access the port 8888 and 8899 (only below ports are attache to the host).  Hope in the documentation those ports also could be added.  Anyway I will move security server to the VM which has the Central Server and try.

`-p 4000:4000 -p 4001:80 -p 4002:9998`

Thanks 
Viraj

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

Please try to run the Central Server with these port mappings:

```
-p 80:80 -p 4000:4000 -p 4001:4001 -p 8888:8888 -p 8899:8899
```

Regards,
Petteri

**Comment by VirajAttanayake** [comment]
Hi Petteri,

Thanks, I will add them and reconfigure again and check.

Regards
Viraj

**Comment by VirajAttanayake** [comment]
Hi Petteri,

I added all the ports as you mentioned. But still cant register the Auth.  Kindly note that the Security server container can reach all port of Central Server Container as shown below (See Figure 2).Please check below error. I have also attached the proxy_ui_api.log.

![image](https://user-images.githubusercontent.com/16677999/133877818-4cb2f783-fc7c-46c4-83f3-82563551f28d.png)

![image](https://user-images.githubusercontent.com/16677999/133878008-a6905ac6-9a92-464f-8e90-c3292e0cf77f.png)


[proxy_ui_api.log](https://github.com/nordic-institute/X-Road/files/7189336/proxy_ui_api.log)

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

Have you checked the `/var/log/xroad/jetty/jetty.log` log file in the Central Server container for details?

Also, are you using some container orchestration platform to run the Central Server container? If yes, you should check that the platform isn't running any processes in the containers that listen to port `8084`. On the Central Server, there's Nginx running as a reverse proxy on port `4001` and it forwards the requests to the management service running on port `8084`.

**Comment by VirajAttanayake** [comment]
Hi Petteri,

Good Morning !

No container orchestration tools at all. We have only install docker on Ubuntu 18.4. No other processes are running. I have also attached the jetty.log, Cant see any errors in the log. 

![image](https://user-images.githubusercontent.com/16677999/134115689-f2ff0ad8-8a32-49ba-a778-557fb1e0bd1c.png)

![image](https://user-images.githubusercontent.com/16677999/134115728-eeedfee4-7245-48a8-94cb-7ce93b619d6b.png)
[jetty.log](https://github.com/nordic-institute/X-Road/files/7200444/jetty.log)

Thanks
Viraj

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

I think that I found the reason for the problem - you have a wrong port mapping for port `4001`. It's currently `4001:80` while it should be `4001:4001`. Also, access to port `4002` isn't required so that mapping can be removed.

![Screenshot 2021-09-21 at 8 33 19](https://user-images.githubusercontent.com/575897/134116718-2793ae60-cb5e-4e90-a738-717974ae6f69.png)

These are the correct mappings:

```
-p 80:80 -p 4000:4000 -p 4001:4001 -p 8888:8888 -p 8899:8899
```

Regards,
Petteri

**Comment by VirajAttanayake** [comment]
Hi Petteri,

As per the documentation, the docker run is as follows. Thats the reason I mapped it like that. I will try the port mapping suggested by you. 

![image](https://user-images.githubusercontent.com/16677999/134118991-85522c3a-8c50-4857-94df-2b30556a10dd.png)

Thanks
Viraj

**Comment by VirajAttanayake** [comment]
Hi Petteri,

Thanks its working after the port change. Hope the documentation can be changed.

Regards
Viraj

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

That's great news! We'll review and update the documentation in the near future. There's some additional complexity related to the port mappings if you want to run multiple containers (e.g., Central Server and one or more Security Servers) on the same host since they use the same ports by default.

Regards,
Petteri
