### ISSUE TITLE
TLS certificate error when accessing Rest Services 

### ISSUE THREAD

**Issue by VirajAttanayake** [nordic-institute/X-Road#1051]
Hi,

We managed to setup two security servers (on Docker) and add them to SUB01 and SUB02 subsystems. We just followed the YouTube (X Road Academy Session 6 - X-Road REST Support - YouTube)  to check the rest services are working. 

![image](https://user-images.githubusercontent.com/16677999/134284448-347320ad-1649-4a51-b2ef-695d10461000.png)

However we get below error when sending the request.

![image](https://user-images.githubusercontent.com/16677999/134284650-443d644c-84e6-458a-8e45-c6a5514b49cb.png)

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

More information about the problem and instructions how to solve it can be found [here](https://confluence.niis.org/display/XRDKB/Client+Specifies+HTTPS+But+Did+Not+Supply+TLS+Certificate). 

In general, different error messages returned by the Security Server are explained [here](https://confluence.niis.org/pages/viewpage.action?pageId=53445058).

**Comment by VirajAttanayake** [comment]
Thanks Petteri, The document exactly tells why this error is coming and how to resolve it.
