### ISSUE TITLE
state is present but all of the following are missing: source

### ISSUE THREAD

**Issue by Dos4dev** [nordic-institute/X-Road#1078]
When I run next command ` ansible-playbook -i hosts/lxd_hosts.txt xroad_dev.yml -vvv`
I receive the next exception:
`"msg": "state is present but all of the following are missing: source"`

<details>
<summary>the full stack trace </summary>

> TASK [build-packages : build docker image for building bionic deb packages] **************************************************************
> task path: /home/virtdev/Desktop/X-Road/ansible/roles/build-packages/tasks/main.yml:2
> <localhost> ESTABLISH LOCAL CONNECTION FOR USER: virtdev
> <localhost> EXEC /bin/sh -c 'echo ~virtdev && sleep 0'
> <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/virtdev/.ansible/tmp `"&& mkdir "` echo /home/virtdev/.ansible/tmp/ansible-tmp-1634892435.6840577-82396-9455462294419 `" && echo ansible-tmp-1634892435.6840577-82396-9455462294419="` echo /home/virtdev/.ansible/tmp/ansible-tmp-1634892435.6840577-82396-9455462294419 `" ) && sleep 0'
> redirecting (type: modules) ansible.builtin.docker_image to community.docker.docker_image
> Using module file /usr/lib/python3/dist-packages/ansible_collections/community/docker/plugins/modules/docker_image.py
> <localhost> PUT /home/virtdev/.ansible/tmp/ansible-local-80255kzvlth1o/tmpeir00zbm TO /home/virtdev/.ansible/tmp/ansible-tmp-1634892435.6840577-82396-9455462294419/AnsiballZ_docker_image.py
> <localhost> EXEC /bin/sh -c 'chmod u+x /home/virtdev/.ansible/tmp/ansible-tmp-1634892435.6840577-82396-9455462294419/ /home/virtdev/.ansible/tmp/ansible-tmp-1634892435.6840577-82396-9455462294419/AnsiballZ_docker_image.py && sleep 0'
> <localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/virtdev/.ansible/tmp/ansible-tmp-1634892435.6840577-82396-9455462294419/AnsiballZ_docker_image.py && sleep 0'
> <localhost> EXEC /bin/sh -c 'rm -f -r /home/virtdev/.ansible/tmp/ansible-tmp-1634892435.6840577-82396-9455462294419/ > /dev/null 2>&1 && sleep 0'
> fatal: [localhost]: FAILED! => {
>     "changed": false,
>     "invocation": {
>         "module_args": {
>             "api_version": "auto",
>             "archive_path": null,
>             "build": null,
>             "ca_cert": null,
>             "client_cert": null,
>             "client_key": null,
>             "debug": false,
>             "docker_host": "unix://var/run/docker.sock",
>             "force": true,
>             "force_absent": false,
>             "force_source": false,
>             "force_tag": false,
>             "load_path": null,
>             "name": "xroad-deb-bionic",
>             "path": "../src/packages/docker/deb-bionic",
>             "pull": null,
>             "push": false,
>             "repository": null,
>             "source": null,
>             "ssl_version": null,
>             "state": "present",
>             "tag": "latest",
>             "timeout": 60,
>             "tls": false,
>             "tls_hostname": null,
>             "use_ssh_client": false,
>             "validate_certs": false
>         }
>     },
>     "msg": "state is present but all of the following are missing: source"
> }
</details>

Steps to reproduce:

1. set up new Ubuntu 20.04 
2. install Docker 20.10.9, build c2ea9bc
3. install Ansible 2.11.6
4. install LXD 4.0.7
5. run `./prepare_buildhost.sh` 
6. run `./update_ruby_dependencies.sh`
7. run `./build_packages.sh` 
8. and the last `ansible-playbook -i hosts/lxd_hosts.txt xroad_dev.yml -vvv`

There is a similar [question](https://stackoverflow.com/q/69506179) in SoF

I am going to create a PR to fix it. 
Is anyone has similar problems?

**Comment by raits** [comment]
Hello, sorry there has not been any feedback on this issue. Since there hasn't been any activity on the issue for a while, I will close it now. If you are still facing issues with this, please feel free to re-open the issue.
