### ISSUE TITLE
Could not connect to any target host

### ISSUE THREAD

**Issue by BlueRoyy** [nordic-institute/X-Road#1086]
HI guys specific error:
“type”: “Server.ClientProxy.NetworkError”,
“message”: “Could not connect to any target host ([https://<public.ip.address>:5500/])“,

I am aware that this is usually caused by ports not being open, the server certificate the security server communicating via its private IP. I have confirmed (using firewall logs and telnet) that the ports (incoming and outgoing) are configured correctly and ALL IP addresses and DNS names are on the certificate in the alternate name field which leaves just one possibility - in theory. 
Our network has public IP addresses NATting to WAN IP addresses which in turn NAT to private IP addresses. Is there anything special required for such a setup that is not mentioned in the documentation? We use this setup for web servers and have no issues but x-road seems to require something more to support this setup

Also note that the Central server is in a totally different network requiring communication via public IP

**Comment by petkivim** [comment]
Hi @BlueRoyy 

When you [register the authentication certificate](https://confluence.niis.org/pages/viewpage.action?pageId=6783483#HowtoConfigureCentralServer?-3.6Registeringtheauthenticationcertificate) of a Security Server by sending an authentication certificate registration request on the Security Server, you must submit the Security Server's IP address or DNS name. The IP address or DNS name is then registered on the Central Server and it's used by other Security Servers when they're connecting to the Security Server. If a service provider Security Server's IP address or DNS name registered on the Central Server is incorrect, the client side Security Server tries to connect to the wrong address and usually it results in `Could not connect to any target host ([https://<public.ip.address>:5500/])` error message. In general, X-Road doesn't require any special network configuration, it's enough to have correct firewall configuration in place and the correct IP or DNS name registered on the provider side Security Server.
