### ISSUE TITLE
Unable to Setup X-Road CS with Remote Database

### ISSUE THREAD

**Issue by YBinMohamed** [nordic-institute/X-Road#1109]
Currently experiencing the error below:
`IP:192.168.207.132,DNS:x-road-cs-remotedb-vm,DNS:x-road-cs-remotedb-vm
/CN=x-road-cs-remotedb-vm -subj
xroad-center: Database and user exists, skipping database creation.
== Baseline: migrating =======================================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

no connection available
arjdbc/jdbc/RubyJdbcConnection.java:298:in `rollback'`

We've tried:
1. Docker Ubuntu with remote PostGres DB
2. BareMetal Ubuntu with remote PostGres DB

For the above, we've tried the guide [here](https://docs.x-road.global/Manuals/ig-cs_x-road_6_central_server_installation_guide.html#251-customize-the-database-properties) and the next section 2.6

We've also tried new/existing users/tables/schema etc but unable to proceed with the same error above.

No issue with local database setup. Is there anything else required to be done for the remote database?

Ubuntu Version" 20.04 (for both bare metal and docker)
X-Road Version: 6.26

**Comment by petkivim** [comment]
Hi @YBinMohamed 

Have you tried creating the database structure [manually](https://github.com/nordic-institute/X-Road/blob/6.26.0/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#annex-d-create-database-structure-manually) before running the installation scripts as described in chapter 2.6?

Also, have you checked that your remote database server is accessible by the Central Server host, e.g., firewall configuration could block the access. You can test the connection by running `telnet <DB_HOST_OR_IP> 5432` on the Central Server host.

**Comment by YBinMohamed** [comment]
Hi @petkivim 

We tried the manual steps and found the problem - missing hstore.control file.
When we setup our postgres database, we used a non-xroad steps and had missed installing the postgresql-contrib. 

After remedying this, it works.
Thanks!
