### ISSUE TITLE
Unable to install X-road 6.26

### ISSUE THREAD

**Issue by YBinMohamed** [nordic-institute/X-Road#1118]
I noticed that there was an update to the **https://artifactory.niis.org/xroad-release-deb** where a new release (v7.0.0) was recently added.
As I had been testing using v6.26.0 for the past month so I would like to continue using that version.

WHen i run **sudo apt-get install xroad-centralserver**, it will always install v7.0.0.0
When I run **sudo apt-get install xroad-centralserver=6.26.0-1.ubuntu20.04**, it will throw error below:
The following packages have unmet dependencies:
 xroad-centralserver : Depends: xroad-center (= 6.26.0-1.ubuntu20.04) but 7.0.0-1.ubuntu20.04 is to be installed
                       Depends: xroad-centralserver-monitoring (= 6.26.0-1.ubuntu20.04) but 7.0.0-1.ubuntu20.04 is to be installed
E: Unable to correct problems, you have held broken packages.

Is it still possible to install v6.26.0 using the repository, or do I have to manully down the deb files now?

**Comment by petkivim** [comment]
Yes, it's still possible to install the version 6.26.0, but you must specify the version number explicitly for all the dependencies:

```
sudo apt-get install xroad-centralserver=6.26.0-1.ubuntu20.04 xroad-center=6.26.0-1.ubuntu20.04 xroad-centralserver-monitoring=6.26.0-1.ubuntu20.04
```

**Comment by YBinMohamed** [comment]
Hi @petkivim 

I ran what you provide and it still threw some dependencies error.
```
The following packages have unmet dependencies:
 xroad-center : PreDepends: xroad-base (= 6.26.0-1.ubuntu20.04) but 7.0.0-1.ubuntu20.04 is to be installed
                Depends: xroad-jetty9 (= 6.26.0-1.ubuntu20.04) but 7.0.0-1.ubuntu20.04 is to be installed
                Depends: xroad-nginx (= 6.26.0-1.ubuntu20.04) but 7.0.0-1.ubuntu20.04 is to be installed
                Depends: xroad-signer (= 6.26.0-1.ubuntu20.04) but 7.0.0-1.ubuntu20.04 is to be installed
                Depends: xroad-confclient (= 6.26.0-1.ubuntu20.04) but 7.0.0-1.ubuntu20.04 is to be installed
```
After revising the command to include the other dependencies above (see below), I was able to install v6.26.0.

`sudo apt-get install xroad-centralserver=6.26.0-1.ubuntu20.04 xroad-center=6.26.0-1.ubuntu20.04 xroad-centralserver-monitoring=6.26.0-1.ubuntu20.04 xroad-base=6.26.0-1.ubuntu20.04 xroad-jetty9=6.26.0-1.ubuntu20.04 xroad-nginx=6.26.0-1.ubuntu20.04 xroad-signer=6.26.0-1.ubuntu20.04 xroad-confclient=6.26.0-1.ubuntu20.04
`
Thanks for the guidance.
