### ISSUE TITLE
Add new Language

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#1119]
I am setup security server version 6.23. Now i want to add new Language in user interface (see my image). Can you support me in this case?
![image](https://user-images.githubusercontent.com/55520717/143859409-01e26872-32de-4fba-9ae5-e76edfc27b61.png)

Thank, BR.

**Comment by petkivim** [comment]
Are you aware that version 6.23 is not officially supported anymore? Version 7.0 is released tomorrow, the 30th of November, and after that the officially supported versions are 6.25, 6.26 and 7.0. Also, the Security Server UI changes in version 6.24.0 and therefore, it would be better to implement any customisations for the new UI directly. It's not only the layout that changes, but also the technologies that are used to implement the UI. Any changes implemented for the version 6.23 UI cannot be used anymore starting from version 6.24.
