### ISSUE TITLE
Configuring REST service - Subsystem Not Found

### ISSUE THREAD

**Issue by YBinMohamed** [nordic-institute/X-Road#1137]
I have my own REST service with two APIs - hello and ping

I Setup a Management Security Server (refer to SSA, 192.168.207.133) who also belongs to subsystem BACKEND
The REST service is behind this SSA and I have configured the BACKEND subsystem to allow the hello API call from subsystem PORTAL.
![image](https://user-images.githubusercontent.com/61005832/146493863-5f34c9ef-fdd1-4d10-bc0e-4199b743f2fa.png)

I have another Security Server (SSB, 192.168.207.152) that belongs to the PORTAL subsystem.
![image](https://user-images.githubusercontent.com/61005832/146494066-a5e69218-7c13-4194-9c91-1bc6c1ecdba8.png)

The setup would have a REST client calling the hello api via X-Road from SSB to SSA.
I had tried the command below:
`curl -i -X GET "http://192.168.207.152:8080/r1/PNG_SG/PNG_MAIN/21609/Portal/xroadtest/api/v1/hello" -H "X-Road-Client: PNG_SG/PNG_MAIN/21609/Backend"`

However, I get Unknown Member error. I tried different permutation but still no luck.

```
HTTP/1.1 500 Server Error
Date: Fri, 17 Dec 2021 05:39:59 GMT
X-Road-Error: Server.ClientProxy.UnknownMember
Content-Type: application/json;charset=utf-8
Content-Length: 162

{"type":"Server.ClientProxy.UnknownMember","message":"Client 'SUBSYSTEM:PNG_SG/PNG_MAIN/21609/Backend' not found","detail":"3fc5d523-d4de-47ab-8e5b-ec3e63844ca9"}
```
I'm sure I must have either missed some configuration in the Security Server or misunderstanding the command to send the REST request. I tried to reference this [ticket ](https://github.com/nordic-institute/X-Road/issues/471)but I am still unsure where I went wrong.

**Comment by YBinMohamed** [comment]
Another information that might help. Both security servers belong to the same owner
![image](https://user-images.githubusercontent.com/61005832/146496192-a32084dc-fb7d-4ede-84ef-09e0337d080c.png)

**Comment by petkivim** [comment]
Hi @YBinMohamed 

The subsystems are incorrect in your `curl` query - they should be the other way around. `xroad-png-cs/PNG_MAIN/21609/Portal` is the client and `xroad-png-cs/PNG_MAIN/21609/Backend` is the service. Also, the `instanceIdentifier` is incorrect in the query ( `PNG_SG` => `xroad-png-cs`). The information above doesn't say what `serviceCode` you've used to publish the API, but I'm assuming that it's `xroadtest`. In that case, the correct query would be:

```
curl -i -X GET "http://192.168.207.152:8080/r1/xroad-png-cs/PNG_MAIN/21609/Backend/xroadtest" -H "X-Road-Client: xroad-png-cs/PNG_MAIN/21609/Portal"
```

Based on the service URL ( `http://192.168.207.115:8080/xroadtest/api/v1/h...`) it seems that you've published only the `hello` endpoint. If you wish to publish both `hello` and `ping` endpoints under the same service code, you should change the service URL to `http://192.168.207.115:8080/xroadtest/api/v1.` In that case, the query would be:


```
curl -i -X GET "http://192.168.207.152:8080/r1/xroad-png-cs/PNG_MAIN/21609/Backend/xroadtest/hello" -H "X-Road-Client: xroad-png-cs/PNG_MAIN/21609/Portal"
```
```
curl -i -X GET "http://192.168.207.152:8080/r1/xroad-png-cs/PNG_MAIN/21609/Backend/xroadtest/ping" -H "X-Road-Client: xroad-png-cs/PNG_MAIN/21609/Portal"
```

**Comment by YBinMohamed** [comment]
@petkivim 

My service code is not xroadtest, so I adapted the command you shared and it runs!!
`curl -i -X GET "http://192.168.207.152:8080/r1/xroad-png-cs/PNG_MAIN/21609/Backend/hello" -H "X-Road-Client: xroad-png-cs/PNG_MAIN/21609/Portal"
I received the expected response for the above.

I intentionally excluded the other API to test and better understand the X-Road ACL and it works too.
`curl -i -X GET "http://192.168.207.152:8080/r1/xroad-png-cs/PNG_MAIN/21609/Backend/ping" -H "X-Road-Client: xroad-png-cs/PNG_MAIN/21609/Portal"`
X-Road-Error: Server.ServerProxy.AccessDenied

Thanks a lot!

By the way, is there a forum/site to raise general queries since usually for github, it typically relates to possible issue with the software. I will be having some other setup related queries soon (and maybe more in the near future) so I want to be sure if I should continue raising them here or somewhere else.

Thanks.

**Comment by YBinMohamed** [comment]
By the way, my testing now moves to HTTPS (HTTP is OK).
When I run the command below to send to the Security Server that is configured for HTTPS, I get an error.
`curl -i -X GET "https://192.168.207.152:8443/r1/xroad-png-cs/PNG_MAIN/21609/Backend/hello" -H "X-Road-Client: xroad-png-cs/PNG_MAIN/21609/Portal"`

Error:
curl: (60) Certificate type not approved for application.

Is there any documentation where to get the cert and prepare it for us by curl or even an external application?

**Comment by petkivim** [comment]
The instructions for configuring HTTPS between an information system and the Security Server are available here:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#9-communication-with-the-client-information-systems

Please note that the required steps are different depending on the role of the information system (service consumer / service provider).

X-Road community Slack is a good channel to raise issues. You can join the community Slack [here](https://x-road.global/join).

Bug reports and enhancement requests can be submitted to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). [Sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account and get access to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1) and [X-Road Backlog](https://jira.niis.org/projects/XRDDEV/).

**Comment by YBinMohamed** [comment]
Thanks. I've registered for Slack access and have taken note of the other links.
