### ISSUE TITLE
Error: Unable to connect to the OCSP responder

### ISSUE THREAD

**Issue by long151** [nordic-institute/X-Road#122]
Hi everyone,
I'm a newbie in X-Road, i have studied xroad two week ago.
I'm trying to build a x-road system follow the guide in document folder.
I just finished installing Central Server, Security Server and CA Server by this detail document:
https://confluence.niis.org/pages/viewpage.action?pageId=6783483#HowtoConfigureCentralServer?-2.InstallingtheSecurityServerformanagementservices
But i can't finish step 3.5 Importing the certificates when i setup security server because the status of "Sign certificate" is  not "good / registered"
![error](https://user-images.githubusercontent.com/48112742/55137505-ba41d700-5163-11e9-91bf-cafb3bbe44b8.png)
When i go to "Diagnostics" menu, OCSP Responders show:
![error2](https://user-images.githubusercontent.com/48112742/55137565-e9584880-5163-11e9-851f-e600e954c714.png)

When i check CA server, nginx service, ocsp service and tsa service  is running. I was installed CA server by following this document. 
https://github.com/ria-ee/X-Road/blob/develop/ansible/TESTCA.md
I don't know how to fix this problem!
Somone help me, please, thanks

**Comment by petkivim** [comment]
Hi @long151 

Have you enabled access from the Security Server to the OCSP service in your firewall configuration? Are you able to access the OCSP service from the Security Server using telnet?

```
telnet 192.168.3.40 8888
```

Regards,
Petteri

**Comment by long151** [comment]
Hi @petkivim 
Thank you for replying me back !
I check status of nginx, ocsp and tsa and they work well
![error3](https://user-images.githubusercontent.com/48112742/55273963-0f691e80-5305-11e9-9e78-c0a318613b81.png)

So I used command "ufw disable" to disable firewall 
And i could ping from Security Server to CA server
But you're right,  i can not using telnet
![error4](https://user-images.githubusercontent.com/48112742/55273968-27d93900-5305-11e9-9507-10fd24290513.png)
Can you tell me what to do ...
Thanks

**Comment by petkivim** [comment]
Hi,

Based on the telnet output the connection should be OK.

**Comment by long151** [comment]
Hi,
when i open "Diagnostics" and check log, it shows:

> 2019-04-01 13:53:45,709 INFO  [Signer-akka.actor.default-dispatcher-253] ee.ria.xroad.signer.OcspClientJob - OCSP-response refresh retry failed, continuing along backoff schedule
2019-04-01 13:54:18,516 INFO  [qtp699780352-27] ee.ria.xroad.common.util.AdminPort - Admin request: /status
2019-04-01 13:54:18,520 INFO  [qtp699780352-27] ee.ria.xroad.signer.SignerMain - handler /status
2019-04-01 13:54:33,013 INFO  [qtp699780352-34] ee.ria.xroad.common.util.AdminPort - Admin request: /status
2019-04-01 13:54:33,014 INFO  [qtp699780352-34] ee.ria.xroad.signer.SignerMain - handler /status
2019-04-01 13:54:45,713 INFO  [Signer-akka.actor.default-dispatcher-259] e.r.x.s.certmanager.OcspClientWorker - OCSP-response refresh cycle started
2019-04-01 13:54:45,713 INFO  [Signer-akka.actor.default-dispatcher-252] ee.ria.xroad.signer.OcspClientJob - Next OCSP refresh retry scheduled in 60 seconds
2019-04-01 13:54:45,716 INFO  [Signer-akka.actor.default-dispatcher-259] e.r.x.s.certmanager.OcspClientWorker - Fetching OCSP responses for 1 certificates
2019-04-01 13:54:45,718 ERROR [Signer-akka.actor.default-dispatcher-259] e.r.x.s.certmanager.OcspClientWorker - Unable to connect to responder at http://192.168.3.40:8888
java.io.IOException: Invalid http response code from responder: 502

**Comment by petkivim** [comment]
Hi,

It seems that Nginx that is proxying TSA and OCSP requests is running, but there's something wrong with the OCSP service. Have you the checked the contents of the `/var/log/ocsp.log` log file?

And have you tried to restart the OCSP service?

Regards,
Petteri

**Comment by long151** [comment]
Hi,
i already restarted OCSP revice in CA server.
But when i checked the contents of the /var/log/ocsp.log, it was empty
nothing showed up on this file

**Comment by long151** [comment]
I don't know how but After reinstalling ca server, OCSP  works well.
thank you for all your support.
