### ISSUE TITLE
Feature request: Notification about expiring certificates

### ISSUE THREAD

**Issue by vahem2lu** [nordic-institute/X-Road#127]
Hi!
Feature request for X-road SecurityServer - automatic messaging (email or web notification) for soon-to-expire certificates. I know about RIAs X-Road-Scripts in Github, but this (expiring certificates) seems to be "issue" for all X-Road users, why not to include it in SS software?

**Comment by petkivim** [comment]
Hi,

Thank you for the feature request. Please submit it to the X-Road Service Desk which is the official channel for enhancement requests and bug reports.

[Sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account and get access to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1) and [X-Road Backlog](https://jira.niis.org/projects/XRDDEV/).

Regards,
Petteri
