### ISSUE TITLE
Error:  URL is expired while installing

### ISSUE THREAD

**Issue by yamakataoka** [nordic-institute/X-Road#129]
Hi everyone,

I have encountered an error when I run `sudo ./prepare_buildhost.sh`.
```

Err:16 http://x-road.ee/misp2/packages xenial/main amd64 Packages
  404  Not Found
Reading package lists... Done
W: The repository 'http://x-road.ee/misp2/packages xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://x-road.ee/misp2/packages/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Could you update the site or script?

Best regards,
Yamato

**Comment by petkivim** [comment]
Hi @yamakataoka 

Could you specify the URL of the X-Road source code repository that you're using? The official source code repository is located at `https://github.com/nordic-institute/X-Road` and it does not contain dependencies to MISP2 or any packages hosted at `x-road.ee` domain.

Regards,
Petteri

**Comment by yamakataoka** [comment]
Thanks for your quick reply. 

I just downloaded yesterday with `git clone https://github.com/nordic-institute/X-Road.git` from https://github.com/nordic-institute/X-Road.

**Comment by petkivim** [comment]
Which branch (or tag) you're trying to build?

Regards,
Petteri

**Comment by yamakataoka** [comment]
`develop` was selected.

Regards,
Yamato

**Comment by petkivim** [comment]
I tried to run the `prepare_buildhost.sh` on a clean Ubuntu 16 host using`develop` branch and I was not able to reproduce the issue. The script does not add the `http://x-road.ee/misp2` repository included in the error message. Probably you have added the repository manually already before. Try to remove the repository and run the `prepare_buildhost.sh` script again after that. It should fix the issue.

Regards,
Petteri

**Comment by yamakataoka** [comment]
I removed `http://x-road.ee/misp2` package repository, then `prepare_buildhost.sh` worked successfully.

Thank you for all your help.

Regards,
Yamato
