### ISSUE TITLE
Install Xroad on redhat 9.

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#1296]
Dear @petkivim!

I want to install Security Server on redhat 9 but i check xroad repo, i dont' see any xroad package for redhat 9. So do xroad support to install on redhat 9? If support, can you send me this guide?

Thank, BR.

**Comment by petkivim** [comment]
Hi @trungnv0412 

Currently, the supported Red Hat versions for the Security Server are RHEL7 and RHEL8. Unfortunately, RHEL9 is not supported.

Best regards,
Petteri
