### ISSUE TITLE
Service Code in service list

### ISSUE THREAD

**Issue by fredycuello** [nordic-institute/X-Road#1297]
In the administration interface of the security server, why does the list of services show the url of the service in the first level? Wouldn't it be clearer to show the service code and when expanding the service see the url?
When the service is SOAP, the current grouping makes sense because there can be several methods inside, but when the services are REST I think it is not necessary.

**Comment by petkivim** [comment]
Hi @fredycuello 

Thank you for the feedback! 

Services are grouped by a service description and therefore, the first level (1.) in the services list shows the service description URL. Instead, the second level (2.) shows the service URL. In case of SOAP services, a single service description may contain multiple service codes that can have different service URLs. In that case, showing the service URL in the first level (1.) wouldn't work. To make the user experience consistent regardless of the service type, the service description URL is shown on the first level for all types of services.

![service_list](https://user-images.githubusercontent.com/575897/178898912-95237a12-f2ab-41fc-a02a-08f903dbec7b.png)

However, REST services don't have a service description like SOAP and OPENAPI3 services. By default, the service description URL and service URL are the same for REST services:

![rest_service](https://user-images.githubusercontent.com/575897/178899638-21c337ba-e2d6-45e2-bb80-eff41c4609ab.png)

Regards,
Petteri
