### ISSUE TITLE
Gradle :Could not create service of type FileHasher

### ISSUE THREAD

**Issue by yamakataoka** [nordic-institute/X-Road#130]
Hello @petkivim,

I get an error again when I build the software and installation packages with `./build_packages.sh`.

```
Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().
```

I find all the process related to gradle by `ps aux | grep gradle`, and then `kill -9 <pid>` them all. But it doesn't work.

Gradle V: 5.3.1

Regards,
Yamato

**Comment by petkivim** [comment]
Hi @yamakataoka 

Do you have Gradle already installed on your host before running the `prepare_buildhost.sh` script? If yes, the problem is probably related to that. Can you try building the software on a clean host and see if that works for you?

Regards,
Petteri

**Comment by yamakataoka** [comment]
Thanks.

I installed already Gradle.
So I will give it go on a clean host.

**Comment by yamakataoka** [comment]
Hello @petkivim , 

I will reinstall Ubuntu on my clean host.
Could you tell me a difference between ubuntu 14, 16 and 18 and a suggestion, when I install X-Road?

**Comment by petkivim** [comment]
Hi @yamakataoka 

Ubuntu 14.04 reaches its End of Life on April 30, 2019. Therefore, X-Road version 6.21.0 is the last version that provides installation packages for Ubuntu 14.04.

X-Road does not support Ubuntu 16.04, but Ubuntu 18.04 is supported instead. It's strongly recommended to use Ubuntu 18.04 for new installations.

Regards,
Petteri

**Comment by yamakataoka** [comment]
Thank you for clear comments.
I fully understand it.
