### ISSUE TITLE
Performance of Security Server

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#1321]
Dear @petkivim!

I use Jmeter call service at SS Provider from SS Consumer. SS Provider including 2 SS, it setup Load balancer. Configulation SS: CPU 32 Core, RAM: 64 GB. Result return with 300 ccus about 110 transactions per second. I use Jmeter call service not use SS, result return with 300 ccus about 1000 transactions per second. I allocate memory for Proxy and Signer follow link https://confluence.niis.org/display/XRDKB/Recommended+Memory+Allocation+for+Proxy and https://confluence.niis.org/display/XRDKB/Recommended+Memory+Allocation+for+Signer. Can you give me solution to debug it?. 
In this case, do OCSP and TSA service affect it? Can I monitor it?

Thank, BR.

**Comment by petkivim** [comment]
Hi @trungnv0412 

Do you mean that the service provider with a single Security Server who **doesn't use LB** is faster than the service provider with an external LB and a Security Server cluster?

>  I use Jmeter call service not use SS, result return with 300 ccus about 1000 transactions per second.

When configuring the memory allocation for the Security Servers, have you followed the instructions for the correct X-Road version? Please note that the way how the memory allocation is configured differs between version 6 and 7. Having incorrect configuration on one the servers could explain the difference. I would start from double checking that the configuration is correct on all the servers and that you have restarted the `proxy` and `signer` processes after updating the configuration.

Have you installed the operational monitoring add-on (`xroad-addon-opmonitoring`) on the Security Servers? You can use the add-on to debug the request duration and failures. More information about the operational monitoring protocol is available [here](https://docs.x-road.global/OperationalMonitoring/Protocols/pr-opmon_x-road_operational_monitoring_protocol_Y-1096-2.html#12-references).

One thing that would explain such a big difference in the performance is different message log configuration. Do all the Security Servers use the same message log configuration? More information about different configuration options is available [here](https://docs.x-road.global/Manuals/ug-syspar_x-road_v6_system_parameters.html#37-message-log-add-on-parameters-message-log).

By default, the Security Server uses batch time-stamping and it doesn't affect the performance. In case you have switched to synchronous time-stamping, it has a big impact on the performance. Synchronous time-stamping is enabled by setting the `message-log.timestamp-immediately` to `true` (default is `false`). Also, OCSP responses are fetched asynchronously. More information about time-stamping and OCSP is available [here](https://www.niis.org/blog/2020/11/20/resisting-failure).

Best regards,
Petteri

**Comment by trungnv0412** [comment]
I test on stand- alone system with 300 ccus, 500 ccus, 1000 ccus, 2000 ccus but transaction per second allway smaller 100. In /etc/xroad/jetty/xroad.mod , i change threads.max=5000. In /etc/xroad/jetty/clientproxy.xml , i change <Set name="maxThreads" type="int">5000</Set>.  In /etc/xroad/jetty/serverproxy.xml , i change <Set name="maxThreads" type="int">5000</Set>. But nothing change.

**Comment by trungnv0412** [comment]
I use 1 SS (consumer and provide) to Test

**Comment by petkivim** [comment]
There are several factors that affect the the Security Server throughput, for example:

- message size
- key length
- message type (SOAP / REST)
- message log configuration (full / metadata / no logging)
- local / external database

Depending on the combination of different factors, the maximum throughput can be under 100 transactions per second.

**Comment by petkivim** [comment]
Also, the bottleneck might the test service that you're using in the performance tests.

**Comment by trungnv0412** [comment]
Dear @petkivim !
In your environment, how many transaction per second xroad can achieve?.  My paradigm: Jmeter -> SS -> IS provider. If i use Jmeter direct call to IS provider with 500 ccus, i have result about 1000 transaction per second.

Thank, BR.

**Comment by petkivim** [comment]
In our environment, we're not running performance tests which aim is to measure maximum performance. Instead, we're monitoring changes in the performance between different X-Road versions. Therefore, our internal results are not very useful in your case. In our tests, the throughput is less than 100 requests per second.

**Comment by trungnv0412** [comment]
Dear @petkivim !
With my case, use default config. Have you solution for me if i want to increasing the number of transaction per second?

Thank, Br.

**Comment by petkivim** [comment]
The easiest way to increase the number of transactions per second is to [disable the message log add-on](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4915570/How+to+Disable+Message+Logging+on+the+Security+Server?src=search). However, it means that the Security Server doesn't provide any evidence of the data exchange. Whether that's OK depends on your business requirements.

Alternatively, you could set up a Security Server cluster with an external load balancer. That's the most efficient way to scale the Security Server performance.

**Comment by trungnv0412** [comment]
Dear @petkivim !

Where param to disable message-log?, Do i must reinstall SS?

Thank, BR.

**Comment by petkivim** [comment]
The link to the instructions was included in my previous comment:

https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4915570/How+to+Disable+Message+Logging+on+the+Security+Server

**Comment by trungnv0412** [comment]
Thank @petkivim !

Thank for your support

Thank, BR.
