### ISSUE TITLE
Opendata Operational monitoring Delay!

### ISSUE THREAD

**Issue by N3tw0rk3r** [nordic-institute/X-Road#1327]
X-Road monitoring data is collected from Estonian X-Road members security servers available by X-Road Center (Republic of Estonia Information System Authority, Riigi Infosüsteemi Amet, RIA) and published as opendata with a delay of 10 days from actual transaction execution time.

Is there any way to change this behavior to configure opendata as a real-time operational monitoring solution ? or Is there any other operational monitoring product that is real time monitoring instead of 10 days delay?

**Comment by petkivim** [comment]
The open data publishing interval is fully configurable and the X-Road Metrics administrator is free to modify the configuration. The data is cleaned and published by the [Anonymizer](https://github.com/nordic-institute/X-Road-Metrics/blob/master/docs/anonymizer_module.md) module. You can change the interval by modifying the Anonymizer [CRON settings](https://github.com/nordic-institute/X-Road-Metrics/blob/master/docs/anonymizer_module.md#cron-settings).

**Comment by N3tw0rk3r** [comment]
Thanks petkivim for your reply,

The calendar at opendata web interface doesn't allow the date to be modified

**Comment by N3tw0rk3r** [comment]
![image](https://user-images.githubusercontent.com/28312192/187412891-c3ddbd66-b24b-4d8c-82e8-4a223b2bfa29.png)

Last day I can choose is past 10 days

**Comment by petkivim** [comment]
The configuration can be changed [here](https://github.com/nordic-institute/X-Road-Metrics/blob/master/opendata_module/etc/settings.yaml#L6). It should update the UI date picker too:

https://github.com/nordic-institute/X-Road-Metrics/search?q=delay-days&type=code

**Comment by petkivim** [comment]
Have you configured your monitoring client (`DEMO/GOV/9999/COLLECTOR`) as the as the central monitoring client on the Central Server? Only the central monitoring client has access permissions to collect monitoring data from all Security Servers of the X-Road instance.

You should upload an XML file with the following content to the Central Server (Global Configuration -> Configuration Parts -> monitoring-params.xml -> Upload):

```xml
<tns:conf xmlns:id="http://x-road.eu/xsd/identifiers"
          xmlns:tns="http://x-road.eu/xsd/xroad.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://x-road.eu/xsd/xroad.xsd">
    <monitoringClient>
        <monitoringClientId id:objectType="SUBSYSTEM">
            <id:xRoadInstance>DEMO</id:xRoadInstance>
            <id:memberClass>GOV</id:memberClass>
            <id:memberCode>9999</id:memberCode>
            <id:subsystemCode>COLLECTOR</id:subsystemCode>
        </monitoringClientId>
    </monitoringClient>
</tns:conf>
```

**Comment by petkivim** [comment]
More information about the central monitoring client is available here:

https://docs.x-road.global/Manuals/ug-cs_x-road_6_central_server_user_guide.html#15-monitoring

**Comment by N3tw0rk3r** [comment]
Thanks petkivim I will try it and send you feedback
