### ISSUE TITLE
Issue: while running ./update_ruby_dependencies.sh

### ISSUE THREAD

**Issue by yamakataoka** [nordic-institute/X-Road#134]
Hello @petkivim,

When I ran `./update_ruby_dependencies.sh` after executing `./prepare_buildhost.sh` on a clean host, I got the massage below.

`./update_ruby_dependencies.sh: line 11: /home/yamatokataoka/.rvm/scripts/rvm: No such file or directory`

Could you detect the reason for that?

Do I have to install those software before running `./prepare_buildhost.sh`?
- OpenJDK / JDK version 8
- Gradle
- JRuby and rvm (ruby version manager)
- GCC  Docker (for deb/rpm packaging)
- LXD (https://linuxcontainers.org/lxd/)
- Ansible 

PS. Host: Ubuntu 18.04 TLS

Regards,
Yamato

**Comment by petkivim** [comment]
Hi @yamakataoka 

`./prepare_buildhost.sh` installs the following dependencies which means that you shouldn't install them manually:

- OpenJDK / JDK version 8
- Gradle
- JRuby and rvm (ruby version manager)
- GCC 
- Docker (for deb/rpm packaging)

`./prepare_buildhost.sh` is supposed to be run as the user who will build the source. The script will ask for user password (using sudo) for installing some new packages as well.

Instead, the following dependencies must be installed manually according to the [instructions](https://github.com/nordic-institute/X-Road/tree/develop/ansible):

- LXD
- Ansible

Regards,
Petteri

**Comment by yamakataoka** [comment]
Thank you. I understood that which software is installed by `./prepare_buildhost.sh`.

Did you have any suggestions for the massage below?

`./update_ruby_dependencies.sh: line 11: /home/yamatokataoka/.rvm/scripts/rvm: No such file or directory`

**Comment by petkivim** [comment]
> ./prepare_buildhost.sh is supposed to be run as the user who will build the source. The script will ask for user password (using sudo) for installing some new packages as well.

Did you run `./prepare_buildhost.sh` as `yamatokataoka`?

**Comment by yamakataoka** [comment]
Yes, I did with sudo command.

**Comment by petkivim** [comment]
Hi @yamakataoka 

And did you run `./update_ruby_dependencies.sh` as `yamatokataoka` with sudo too?

I tried to repeat the steps on a clean Ubuntu 18 host on AWS, but I was not able to reproduce the issue.

```
$ git clone https://github.com/nordic-institute/X-Road.git
$ cd X-Road/src
$ ./prepare_buildhost.sh
$ ./update_ruby_dependencies.sh
```

I did the test using the following AMI: `ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190212.1 (ami-090f10efc254eaf55)`

Regadrs,
Petteri

**Comment by yamakataoka** [comment]
Thank you for your reply.
Yes, I did it too.

Thank you for letting me know and trying it out on your side.

One question: Is there any difference between desktop edition and server edition, when we try to install X-Road?

**Comment by petkivim** [comment]
> Is there any difference between desktop edition and server edition, when we try to install X-Road?

X-Road can be installed and run on both.

**Comment by yamakataoka** [comment]
Thank you for reply with details.

I will try it out again with bootcamp of Mac.

**Comment by yamakataoka** [comment]
the problem was solved as I followed below suggested by @petkivim.

`$ git clone https://github.com/nordic-institute/X-Road.git
$ cd X-Road/src
$ ./prepare_buildhost.sh
$ ./update_ruby_dependencies.sh`

Actually, I did `sudo ./prepare_buildhost.sh`. So that's my bad.

Thank you for all your help.
