### ISSUE TITLE
As an X-Road administrator I would like to be able to map LDAP groups to X-Road user groups so that I can better control access rights

### ISSUE THREAD

**Issue by raits** [nordic-institute/X-Road#1366]
The previous ticket ([XRDDEV-1699](https://nordic-institute.atlassian.net/browse/XRDDEV-1699)) concluded, that configuring X-Road to use LDAP is quite simple by setting up the LDAP module for [PAM](https://en.wikipedia.org/wiki/Linux_PAM). The limitation is that in that case, the users defined in LDAP would get the same X-Road groups added to them for all servers using LDAP for authentication.

As an example, if an X-Road Member has 3 Security Servers:

- ss-dev
- ss-test
- ss-prod

And has a user john, with the following groups attached:

- xroad-system-administrator
- xroad-service-administrator
- xroad-securityserver-observer

Then there is no way to say that it should map the following way to the Security Servers:

- xroad-system-administrator → ss-dev
- xroad-service-administrator and xroad-securityserver-observer → ss-test
- xroad-securityserver-observer → ss-prod

Currently, the user john would have all three groups on all three servers. Instead, we should add configurable properties to the Security Server UI/API (src/proxy-ui-api) configuration, that allow us to map certain groups to other groups, e.g:

- ss-dev-admin = xroad-system-administrator
- ss-test-service-admin = xroad-service-administrator,xroad-securityserver-observer
- ss-prod-observer = xroad-securityserver-observer

The aim of this ticket is to implement such a capability. In the previous study it was concluded that a good candidate to do this would be in the following piece of code: https://github.com/nordic-institute/X-Road/blob/develop/src/common-rest-api/src/main/java/org/niis/xroad/restapi/auth/PamAuthenticationProvider.java#L116

The JIRA ticket this issue was created from can be found here: https://nordic-institute.atlassian.net/browse/XRDDEV-1997

Acceptance criteria:

- [x] The administrator is able to specify group mappings in the X-Road Security Server UI/API properties
  - [x] https://docs.x-road.global/Manuals/ug-syspar_x-road_v6_system_parameters.html#39-management-rest-api-parameters-proxy-ui-api
- [x] An LDAP group can match to one or more Security Server groups
- [x] When a user logs in, any groups associated with the user are checked for the mapping and if found, augmented by the additional mapped group(s)
- [x] Original X-Road groups are not allowed to be redefined in properties: xroad-security-officer, xroad-registration-officer, xroad-service-administrator, xroad-system-administrator, and xroad-securityserver-observer
- [x] In a Security Server cluster, the user group restrictions on secondary nodes must be respected (item #9) and NOT overridden by the mapping:
  - [x] https://docs.x-road.global/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.html#33-replica-installation
- [x] Documentation is updated:
  - [x] https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#2-user-management
  - [x] https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-syspar_x-road_v6_system_parameters.md#39-management-rest-api-parameters-proxy-ui-api

[XRDDEV-1699]: https://nordic-institute.atlassian.net/browse/XRDDEV-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ImmaculatePasta** [comment]
Hi, I found this under a search for "api documentation help wanted" - but it sounds more like a dev job?
Please let me know if there are any tasks for API documentation and I can help, cheers

**Comment by ImmaculatePasta** [comment]
Hi @raits 
Thanks for clarifying and best of luck with your project. It sounds very interesting. 
Cheers
