### ISSUE TITLE
Error: Failed to get time stamp from any time-stamping providers

### ISSUE THREAD

**Issue by yamakataoka** [nordic-institute/X-Road#138]
Hello @petkivim,

I tried to download transaction log file along with [Signed Document Download and Verification Manual](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-sigdoc_x-road_signed_document_download_and_verification_manual.md).

However, my test TSA seems not working according to `Failed to get time stamp from any time-stamping providers` error massage responding from 
`https://10.183.203.87/asic?queryId=3ebaeb5f-94e6-4398-b93f-6228bc3adf78&xRoadInstance=DEMO&memberClass=GOV&memberCode=1234&subsystemCode=SUB2&force`.

Also, Timestamping status on Diagnostics was Ok.
![Screenshot](https://user-images.githubusercontent.com/34284486/56871976-bf45bf00-6a5e-11e9-8abd-767f188ff727.png)

How does the test timestamp work?

P.S. X-Road Test Service and X-Road Test Client is used as a testing tool which creates responses and requests.
P.S.S hosts following
test service: Ubuntu 16.04 LTS
test client: Ubuntu 18.04 LTS
X-Road: Ubuntu 18.04 LTS

**Comment by petkivim** [comment]
Hi @yamakataoka 

The diagnostics only tests the connection between Security Server and TSA on a network level - when the status is OK, it means that Security Server is able to issue a TCP connection to TSA. It does not test if TSA is operating normally.

Have you tried to [restart](https://github.com/nordic-institute/X-Road/blob/develop/ansible/TESTCA.md#4-restart-nginx-ocsp-and-tsa-services) the TSA service or the host running it?

Regards,
Petteri

**Comment by yamakataoka** [comment]
Thank you for your advice.

I tried to restart host and nginx with `lxc restart demo-ca` and `systemctl restart nginx`.
When running `sudo /sbin/start ocsp` and `sudo /sbin/start tsa` on the lxd container:
`sudo: /sbin/start: command not found`

Could you tell me how to call `sudo /sbin/start ocsp` and `sudo /sbin/start tsa` to start the jobs?

Regards,
Yamato

**Comment by petkivim** [comment]
Have you tried `$ service tsa restart`? 

```
$ ps -ef  | grep tsa
ocsp      1364     1  0 08:51 ?        00:00:00 /usr/bin/python /home/ca/TSA/tsa_server.py
root      1367  1228  0 08:51 ?        00:00:00 grep --color=auto tsa
```

Regards,
Petteri

**Comment by yamakataoka** [comment]
Thank you.
Now, I have tried it both of them. 
It seems good.
```
root@demo-ca:~# service tsa restart
root@demo-ca:~# ps -ef | grep tsa
ocsp       309     1  0 09:12 ?        00:00:00 /usr/bin/python /home/ca/TSA/tsa_server.py
root       336   294  0 09:18 ?        00:00:00 grep --color=auto tsa
```
Could you tell another way to check that the tsa work correctly?

**Comment by petkivim** [comment]
@yamakataoka 

We discovered that there was a [bug](https://jira.niis.org/browse/XRDDEV-501) in the test CA which caused TSA to fail on Ubuntu 18 host. The bug is fixed now and the fix is available in the `develop` branch.

Regards,
Petteri

**Comment by yamakataoka** [comment]
Hi @petkivim ,

Thank you for your response and all your team.
The log was successfully downloaded!

Regards,
Yamato
