### ISSUE TITLE
Security Server Multi-Tenancy

### ISSUE THREAD

**Issue by N3tw0rk3r** [nordic-institute/X-Road#1391]
Hello,

How to configure SS in Multi-Tenancy Architecture, I mean how to give each security server client access to his services only when he login to Security Server Portal ?

**Comment by petkivim** [comment]
Hi @N3tw0rk3r 

The Security Server supports multi-tenancy which means that multiple organisations can share the same Security Server. In that case, each organisation must have its own subsystem or multiple subsystems registered on the Security Server. In addition, each organisation must have its own sign key and certificate on the Security Server.

In a multi-tenancy setup it's extremely important to use mTLS in the connections between the client information system and the Security Server. When a new subsystem is registered, mTLS is enabled by default in the subsystem settings. More information about the topic is available [here](https://docs.x-road.global/Manuals/ug-ss_x-road_6_security_server_user_guide.html#9-communication-with-the-client-information-systems).

Unfortunately, the Security Server UI and REST management API do not support authorization on a member level. In other words, it's not possible to give an administrator access to a specific member's configuration only. Instead, the Security Server supports [role based authorization](https://docs.x-road.global/Manuals/ug-ss_x-road_6_security_server_user_guide.html#2-user-management) on a feature level. Each administrator can have one or more roles that define the features the administrator can access. Within those features the administrator is able to access all the members' and subsystems' configuration.

Best regards,
Petteri

**Comment by N3tw0rk3r** [comment]
Thanks Petteri for your great explanation, wonderful as usual
