### ISSUE TITLE
WSDL which is not aligned with X-Road Message Protocol for SOAP is imported into security server without errors

### ISSUE THREAD

**Issue by arattur** [nordic-institute/X-Road#1552]
**Software version**: Docker image xroad-security-server-standalone:latest (X-Road Security Server version 7.2.1-1.ubuntu20.04)

**More detailed description of the problem that includes:**
Following WSDL [ejs_wsdl.txt](https://github.com/nordic-institute/X-Road/files/10905548/ejs_wsdl.txt) is not alligned with [X-Road Message Protocol for SOAP](https://github.com/nordic-institute/X-Road/blob/develop/doc/Protocols/pr-mess_x-road_message_protocol.md#3-describing-services). For example mandatory header elements (client, service etc) are missing and Remote Procedure Call style binding (soap:binding style="rpc") is used instead of a mandatory Document/Literal-Wrapped. Importing this WSDL should result in validation error, but it is imported as valid.

**Steps to reproduce the issue:** 
1. Log into Security Server as Administrator
2. Choose _TestService_ client
3. Under _Services_ tab import following WSDL: [ejs_wsdl.txt](https://github.com/nordic-institute/X-Road/files/10905548/ejs_wsdl.txt)
4. WSDL is imported as valid without any errors

**Expected result:** WSDL which does not confirm with X-Road Message Protocol for SOAP should not pass validation and according error should be returned to Security Server Administrator

**Actual result:** WSDL is imported into Security Server without any errors

**Comment by petkivim** [comment]
Hi @arattur! Thank you for submitting the issue.

X-Road uses the [Apache CFX WSDL Validator](https://cxf.apache.org/docs/wsdlvalidator.html) component to validate WSDLs when 1) services are added to the Security Server or 2) existing services are refreshed. The WSDL validator completes the following checks:

> The wsdlvalidator validates whether a WSDL document is well-formed and schema conformed as noted by the following checks.
> - Check the WSDL document for [XML well-formedness](http://en.wikipedia.org/wiki/XML#Well-formedness_and_error-handling).
> - Validate the WSDL document against its [XML schema](http://en.wikipedia.org/wiki/XML#Schemas_and_validation).
> - Validate the WSDL document using some of the semantic rules defined in the [WSDL specification](http://www.w3.org/TR/wsdl).
> - Validate the WSDL document against custom validation rules, such as those defined by the Web Services Interoperability (WS-I) organization (i.e. [WS-I Basic Profile](http://www.ws-i.org/profiles/basicprofile-1.1.html) rules).
> - Validate the WSDL against strange exceptions, incorrectly generated code and general bad WSDL issues.

Instead, the WSDL validator doesn't do any X-Road-specific validations. The WSDL validator component was updated in [X-Road version 6.20.0](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4915387/X-Road+v6.20.0+Release+Notes) and the validator that was used in X-Road versions before 6.20.0 did some X-Road-specific validations. However, those validations were dropped in version 6.20.0. More information about the change is available [here](https://nordic-institute.atlassian.net/browse/XRDDEV-8).

All in all, the behavior that you're describing is a feature, not a bug.

**Comment by arattur** [comment]
@petkivim thank you for thorough clarification!
