### ISSUE TITLE
Ubuntu package 'xroad-base': logic error in 'xroad-base.preinst'

### ISSUE THREAD

**Issue by uvelokk** [nordic-institute/X-Road#1717]
May I pay your attention to a logic error in the file 'xroad-base.preinst'.

If you change the environmental variable 'LC_ALL' by changing the file '/etc/environment' in server, then the criterion of truth should be the existence of that string in the same file and not the environmental variable 'LC_ALL'.

```sh
if grep -q '^LC_ALL=.*UTF-8$' /etc/environment ; then
  echo "system locale set to UTF-8 compatible in /etc/environment already."
else
  if grep -q '^LC_ALL=.*$' /etc/environment ; then
    echo "setting system locale to LC_ALL=en_US.UTF-8 in /etc/environment"
    sed -i -r 's/^(LC_ALL=).*/\1en_US.UTF-8/' /etc/environment
  else
    echo "setting system locale to LC_ALL=en_US.UTF-8 in /etc/environment"
    echo "LC_ALL=en_US.UTF-8" >> /etc/environment
  fi
fi
```

The variable of a session may be changed as well if that is mandatory:

```sh
if [[ $LC_ALL =~ "UTF-8"$ ]]; then
  echo "session locale set to UTF-8 compatible already."
else
  echo "setting session locale to LC_ALL=en_US.UTF-8"
  export LC_ALL="en_US.UTF-8"
fi
```

**Comment by andresrosenthal** [comment]
Hi @uvelokk!

Under normal circumstances this shouldn't be a problem, but you're correct.
Currently as it is, it has a potential loophole which might produce unwanted results & your suggestion would improve that.

Regards,
Andres

**Comment by andresrosenthal** [comment]
The [suggested improvement](https://github.com/nordic-institute/X-Road/pull/1719) will be introduced in version 7.4.0

**Comment by andresrosenthal** [comment]
The [suggested improvement](https://github.com/nordic-institute/X-Road/pull/1719) will be introduced in version 7.4.0
