### ISSUE TITLE
Problem with calling rest service between security Server 1 and Security Server 2 

### ISSUE THREAD

**Issue by Fran765** [nordic-institute/X-Road#1728]
Hi, X-Road support team,
I’ve install the X-Road (version 7.2.2 Ubuntu 22.04) with following info:

* central server
![Captura desde 2023-06-22 10-15-49](https://github.com/nordic-institute/X-Road/assets/110545539/74ac914c-6ccf-40de-98e8-a1de77502b07)

* security server 1
![image](https://github.com/nordic-institute/X-Road/assets/110545539/1e724a46-6f17-433a-84d9-38e0fb59e404)

* security server 2
![image](https://github.com/nordic-institute/X-Road/assets/110545539/e8002c71-d215-49c2-a1b3-4d592daaff44)

*In SS1 I configue REST API in client "Provider" and grant ACCESS RIGHT for SUBSYSTEM "Becas" of SS2 and SUBSYSTEM "Provider" of SS1.
![image](https://github.com/nordic-institute/X-Road/assets/110545539/03069745-0a72-4436-a4b7-dee4b4aae6cc)

*But when I make request to the API from Postman below:
![image](https://github.com/nordic-institute/X-Road/assets/110545539/aacccf8d-ac32-4bf0-ae86-ab717d4e60f0)

Please help me fix this isssue.

**Comment by petkivim** [comment]
Hi @Fran765 

You're sending the request to the wrong Security Server. Now you're sending it to the provider side Security Server (`10.242.215.10`) while you should be sending it to the consumer side Security Server (`10.242.215.236`) where the client subsystem (`POST/EDU/4321/BECAS`) is registered.

**Comment by Fran765** [comment]
ooh, thank you so much!
I thought that I should sending the request to the Security Server where the service was registered.
I Forget that firts I have to send the request to the Security Server where the consumer is registered.
I close the topic.
