### ISSUE TITLE
Error in setting up the TESTCA

### ISSUE THREAD

**Issue by KaHustOwOd** [nordic-institute/X-Road#1754]
Hi everyone, can you help me. I'm a newbie to this. I tried to manually configure the CA in my terminal. I followed the steps in the TESTCA.md but i'm stuck at the "sudo systemctl start ca ocsp tsa" . The output is kind of like unit ocsp.service is not found. At the preliminary step, I only download the package "roles/xroad-ca" to my root machine. I wonder if is there anything that requires missing in the package I downloaded. Do I have to download the other packages in the folder "roles" to get the full functional service?

**Comment by raits** [comment]
Hello,

Manually setting up the test CA is unfortunately not documented as well as it could be. If your aim is to just set up a quick test / development environment locally, I would highly suggest using the ansible scripts to set up the environment in LXD instead.

As for this question, you probably have not copied the service files to the correct location (from `bionic-files/lib/systemd/system`) or have not run the `sudo systemctl daemon-reload` command to reload the services. If you want to continue with the manual steps, the easiest way might be to follow the ansible task to see what steps it takes: https://github.com/nordic-institute/X-Road/blob/develop/ansible/roles/xroad-ca/tasks/main.yml.

**Comment by KaHustOwOd** [comment]
Thank you for your advice, sir but I have the mission to configure CA manually :((. Yet, I couldn't find the path of bionic-files. What I did is copy the ./lib/systemd/system to my rootmachine's lib. And the unit ca, tsa, ocsp.service are all not found yet.

**Comment by KaHustOwOd** [comment]
Thank you for your urgent help sir @raits, my problem has been solved now. I had copied multiple lib_files to different folders in my rootmachine..
