### ISSUE TITLE
How to add a new security server in the x-road ecosystem

### ISSUE THREAD

**Issue by Fran765** [nordic-institute/X-Road#1776]
Hi, X-Road support team.
I've an ecosystem up and running with two securities servers.
I would like to learn how to add new securities servers to the work ecosystem.

I tried modifying the "lxd_host.txt" file found in the "hosts" folder of ansible, adding a new security server to it.
![Captura desde 2023-08-17 10-21-00](https://github.com/nordic-institute/X-Road/assets/110545539/167c64e5-586c-40e3-a38b-2d48b9c7bb61)

run to the command "ansible-playbook  -i hosts/lxd_hosts.txt xroad_init.yml" and then "lxc list"
![Captura desde 2023-08-17 10-21-48](https://github.com/nordic-institute/X-Road/assets/110545539/bced1ff5-0ef1-4686-b6e6-92c4e49c8be2)

but when looking for it with its ip it does not appear
![Captura desde 2023-08-17 10-22-51](https://github.com/nordic-institute/X-Road/assets/110545539/d337eac6-3f79-4b35-aab7-11159a4da59b)

**Comment by petkivim** [comment]
Hi @Fran765 

Have you tried to access the UI using HTTPS (`https://10.242.215.243:4000`)? The UI only supports HTTPS, HTTP is not supported.

Best regards,
Petteri

**Comment by Fran765** [comment]
I've tried both protocols and it still doesn't work.
Is the way I try to add the new security server correct?
The initial configuration of the ansible is done as it says in the git and then I want to add the new security server without losing the initial configuration of the old ones.

**Comment by petkivim** [comment]
The way how you added the new Security Server is correct. However, you could comment out the other hosts in `lxd_host.txt` so that only the line that contains the new host is active. But even if you reinstall X-Road on the other hosts, you don't lose the initial configuration.

Have you tried to look at the `/var/log/xroad/proxy_ui_api.log` file for details inside the `post-ss3` container?

**Comment by Fran765** [comment]
I tried following that post-ss3 container path and the container is empty, there is only one folder called "snap".

what is this about?
in the other security servers (post-ss1 and post-ss2) if I can enter that path indicates

**Comment by petkivim** [comment]
It means that for some reason the Security Server wasn't installed in the container. You could destroy the container and run the Ansible script again. This time, please comment out the other containers in the hosts file.

**Comment by Fran765** [comment]
Run the commands lxc stop post-ss3 and then lxc delete post-ss3. 
Then edit the file where each container is and comment out the other containers as indicated.
I ran the command "ansible-playbook -i hosts/lxd_hosts.txt xroad_init.yml" again and it still doesn't work.

![Copia de Captura desde 2023-08-22 12-18-42](https://github.com/nordic-institute/X-Road/assets/110545539/f22e0381-a336-46f9-9e47-f699f2fdad19)

**Comment by petkivim** [comment]
Based on the output, the error is related to the `post-cs` container. Are you sure you edited the `hosts/lxd_hosts.txt` file?

The contents of the file should look something like this:

```
#central servers (ubuntu lxd containers)
[cs_servers]
#post-cs ansible_connection=lxd

#configuration proxies (ubuntu lxd containers, optional)
[cp_servers]
#xroad-lxd-cp ansible_connection=lxd

#certification authority, time stamping authority and ocsp service server for testing purposes (ubuntu)
[ca_servers]
#post-cs ansible_connection=lxd

#security servers (ubuntu lxd containers)
[ss_servers]
#post-ss1 ansible_connection=lxd
#post-ss2 ansible_connection=lxd
post-ss3 ansible_connection=lxd

[ss_servers:children]
centos_ss

#security servers (centos lxd containers, not supported in variant ee)
[centos_ss]
#xroad-lxd-rh-ss1 ansible_connection=lxd

#container host
[lxd_servers]
localhost ansible_connection=local

#compilation host
[compile_servers]
localhost ansible_connection=local

### vars ###
[ss_servers:vars]
variant=vanilla
```

**Comment by Fran765** [comment]
Hi @petkivim
I have the same document as the example, but it still doesn't work for me. I decided to start the project in Docker.
Thank you.
