### ISSUE TITLE
wrong key usage

### ISSUE THREAD

**Issue by crimildom83** [nordic-institute/X-Road#1780]
![WhatsApp Image 2023-08-25 at 13 16 58](https://github.com/nordic-institute/X-Road/assets/64681610/aab19422-9b75-4e25-85de-6ae22e5c11db)
Hi everyone, i am trying to run the SIGNING ADD Key on the Security Server and i getting this error: Wrong Key Usage.
Before i was with the OCSP id address that was wrong and the Certification Service could not get the Test CA automatically.
So after changing the ip address its Ok.
So, I need help to understand where is the error.
Wrong Key usage ID: 813b256e3536853.
Please.

**Comment by petkivim** [comment]
Hi @crimildom83! Have you checked the `/var/log/xroad/signer.log` log file for details?

**Comment by crimildom83** [comment]
Hi, @petkivim! I already found the solution by changing the OCSP IP and also the https to http. 
I tried to verify the /var/log/xroad/signer.log and there was an error about OCSP IP. 
Tks a lot for the support.
