### ISSUE TITLE
Server DNS nane (CN)

### ISSUE THREAD

**Issue by crimildom83** [nordic-institute/X-Road#1781]
I would like also to know in all these containers which is DNS Server name:  Teste-CA, Teste-CS, Teste-SS1, and Teste-SS2.
is Teste-CS a DNS?

**Comment by crimildom83** [comment]
Hi @petkivim! is it correct to use the Teste-CS IP container as DNS? Also, I made it manually using (nano /etc/NetworkManager/dnsmasq.d), but it does not accept to use of the container name to access the central server CS.  
Thank you for your support.

**Comment by petkivim** [comment]
Hi @crimildom83! You should use the `/etc/hosts` file to define DNS entries locally. More information can be found [here](https://man7.org/linux/man-pages/man5/hosts.5.html).
