### ISSUE TITLE
expose IP containers

### ISSUE THREAD

**Issue by Fran765** [nordic-institute/X-Road#1786]
Is it possible to expose the IP of these containers to the network to be accessed from another machine?

![261322754-bced1ff5-0ef1-4686-b6e6-92c4e49c8be2](https://github.com/nordic-institute/X-Road/assets/110545539/c00e8b08-2f49-4176-a053-8be2efadb2f3)

Specifically, we want to expose the central service to be able to consume it from another machine where we have a security server made with docker.

**Comment by petkivim** [comment]
Hi @Fran765! Yes, the containers can be configured to connect to the internet and be accessible from outside the host system. However, in the case of X-Road, they're meant for local development/testing only and therefore, we don't provide support for such configuration. Here's some resources that should help you with the configuration:

* https://lxdware.com/forwarding-host-ports-to-lxd-instances/
* https://bobcares.com/blog/access-lxc-container-from-outside/

**Comment by Fran765** [comment]
Thanks for the answer, I'll be investigating and consulting any questions.
