### ISSUE TITLE
Asking help about the Error Maximum Loggable Size

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#179]
Dear XRoad,
May I ask about this error? Why I cannot upload the file that its size is more than 10MB?
How could we change that maximum to more than that?
{
    "type": "Server.ClientProxy.IOError",
    "message": "LoggingFailed: Message size exceeds maximum loggable size",
    "detail": "560044e6-e89f-4e6c-b00a-e4678b940cbc"
}

Thanks in advanced.
Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Dear Dara,

By default, all the messages are stored in the message log database. In case the Security Server processes a big number of messages, the messages will require a significant amount of disk space. Therefore, the default value of the allowed message size is set intentionally low.

However, the default size can be overridden using the `message-log.max-loggable-body-size` property. Alternatively, also `message-log.truncated-body-allowed` property can be used to solve the problem. Third alternative is to disable logging of the message body completely setting the `message-log.message-body-logging` property to `false`. All the mentioned properties are documented [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Protocols/pr-meta_x-road_service_metadata_protocol.md#2-retrieving-list-of-service-providers). 

Instructions for overriding the default values can be found [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-syspar_x-road_v6_system_parameters.md#21-changing-the-system-parameter-values-in-configuration-files).

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear Petteri
Thanks your information. And it work now well now.

Best Regards,
Dara Penhchet
