### ISSUE TITLE
Change security server ip

### ISSUE THREAD

**Issue by Fran765** [nordic-institute/X-Road#1818]
Hello!
Register the security server on 'MANAGEMENT' from the center server with the ip provided by the lxc container. I need to change this IP to the public IP of the server.
How can I change it and what would be the steps to reconfigure the Security Server so that the other security servers can communicate with the new IP of the management security server?
Many thanks!
![image](https://github.com/nordic-institute/X-Road/assets/110545539/5860e429-6745-47cf-bfd8-9acc74d9fb82)

**Comment by Fran765** [comment]
Hi @petkivim! I was able to successfully change the security server ip!

Now I have a problem wanting to register the 'CONSUMER' subsystem
![image](https://github.com/nordic-institute/X-Road/assets/110545539/4adf19f0-a59f-4264-9104-84f7f127a5bf)

I tried to see the logs to find out where the error came from but I can't find which one I have to see.

**Comment by petkivim** [comment]
Hi @Fran765! Based on the error message, the management services' access rights are missing or incorrect on the management Security Server. Configuring the management services is explained here:

https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0#3.8-Configuring-the-management-services

**Comment by Fran765** [comment]
In the services of the MANAGEMENT subsystem I only choose this same
![image](https://github.com/nordic-institute/X-Road/assets/110545539/6f0041c9-cd26-4282-b3ac-ba029fd2b8ea)

and Doing the steps to add the 'TEST' also gives me the same error.
![image](https://github.com/nordic-institute/X-Road/assets/110545539/f2b4bc03-c94b-45b5-badd-0f096c8cb592)

**Comment by petkivim** [comment]
Please check that the Verify TLS Certificate checkbox is unchecked and that the Service URL matches with the Central Server Settings -> System Settings -> Management Services -> Central Server address.

![verify_tls_certificate](https://github.com/nordic-institute/X-Road/assets/575897/3c38fb0c-7f95-41e3-8988-3238f76526d6)

**Comment by petkivim** [comment]
It's this part of the instructions:

> Press the > in front of the WSDL to show the services it contains.
> * Select authCertDeletion from the services list by clicking the service code.
> * Service URL - copy from the Central Server Settings -> System Settings -> Management Services -> Central Server address. 
> * Timeout - leave to default.
> * Verify TLS Certificate - unchecked (remove the tick if checked).
> * Apply to All in WSDL - check all boxes to perform the changes to all the WSDL services.
> * Press Save.

**Comment by Fran765** [comment]
Yes, that configuration is like this and even the Verify TLS Certificate is unchecked.

**Comment by petkivim** [comment]
And does the management services list look like this (all the locks are yellow, they have the same URL, and the URL matches the Central Server address in the Central Server System Settings view)?

![management_services](https://github.com/nordic-institute/X-Road/assets/575897/9e17ae08-abc6-4f77-afbb-9f4c73ecb4e7)

**Comment by Fran765** [comment]
Yes, the 'Central Server Address' URL is copied and pasted into the list services.
All the yellow locks were also left.

It's okay for the WSDL to requiered "http" and the ' Central Server Address' URL to be "https"?

**Comment by petkivim** [comment]
> It's okay for the WSDL to requiered "http" and the ' Central Server Address' URL to be "https"?

Yes, that's normal.

Have you looked at the management Security Server proxy log for details? Also, you could try to change the management Security Server proxy's [logging level](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4916392/How+to+change+Security+Server+logging+levels) to `DEBUG` to see more detailed information about the problem.
