### ISSUE TITLE
I found this tiny typo :) Just wanted to let you know...

### ISSUE THREAD

**Issue by gardart** [nordic-institute/X-Road#1823]
Here is a typo, there is a tick symbol in the string "Management Services' Security Server"
https://github.com/nordic-institute/X-Road/blob/57991d98c138f9f3a1c02d82e6f07e29b66efd0e/src/central-server/admin-service/ui/src/locales/en.json#L663

**Comment by petkivim** [comment]
Hi @gardart! Thank you for reporting the observation. Actually, it's not a typo. The apostrophe is used because "Management Services" is a [plural possessive noun](https://www.grammarly.com/blog/possessive-nouns/) and therefore, the apostrophe is added to the end.
