### ISSUE TITLE
Required field 'protocolVersion' is missing

### ISSUE THREAD

**Issue by Konservin** [nordic-institute/X-Road#1853]
protocolVersion is set in headers, but response error is that it is missing. What might cause this?
![image](https://github.com/nordic-institute/X-Road/assets/5410710/a9ab8362-629b-4877-839d-f344e76a4626)

**Comment by raits** [comment]
Hey @Konservin!

Unfortunately I am not familiar with the output on the screenshot. Could you please clarify what framework you are using and if it would be possible to get the actual SOAP message that is generated based on the displayed input?

**Comment by Konservin** [comment]
[test_req.xml.txt](https://github.com/nordic-institute/X-Road/files/13319294/test_req.xml.txt)

Thank You for looking into it.
Platform is Symfony 4.4, generated XML is attached with replaced XXXXs.

**Comment by petkivim** [comment]
Hi @Konservin! Does the response message returned by your service contain all the same headers that the request message has? The error message indicates that the response message doesn't have the `protocolVersion` header. The service is responsible for adding the required headers to the response message - the Security Server doesn't do it automatically. Here's an example of a [request](https://github.com/nordic-institute/xrd4j/blob/develop/example-adapter/examples/helloServiceRequest.xml) / [response](https://github.com/nordic-institute/xrd4j/blob/develop/example-adapter/examples/helloServiceResponse.xml) message pair.

**Comment by Konservin** [comment]
Hi!
No, service returns an error message that says "Required field 'protocolVersion' is missing"

**Comment by petkivim** [comment]
Thanks for the clarification! The request that you shared earlier looks good to me and it includes the `protocolVersion` header field correctly. Unfortunately, I'm not familiar with the framework you're using to implement the service and therefore, it's difficult to say what could cause the issue.

**Comment by jalmar-spin** [comment]
This error occurs because there are some incorrect namespaces in the request.

The namespaces should be:
* `http://x-road.eu/xsd/xroad.xsd` instead of `https://x-road.eu/xsd/xroad.xsd` 
* `http://x-road.eu/xsd/identifiers` instead of `https://x-road.eu/xsd/identifiers`

And the namespace for element `detailandmed_v1` should be `http://arireg.x-road.eu/producer/` instead of `http://arireg.x-road.eu`.

**Comment by raits** [comment]
Closing this issue since it is inactive.
