### ISSUE TITLE
Xroad Security Server

### ISSUE THREAD

**Issue by KandeAbdoul** [nordic-institute/X-Road#1868]
Hello,
In this [tutorial](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4916223/How+to+Configure+Central+Server) in section 3.4, when adding a key,  it asks for the Organization Name (O) for the central server. I don't know how to obtain it.
Can i have an example configuration?

Regards,

**Comment by petkivim** [comment]
Hi @KandeAbdoul! It's the name of the organisation who owns the Security Server. 

By the way, there's a newer version of the configuration guide available. If you're using the X-Road version 7.3, please refer to the newer version of the guide:

https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0

Best regards,
Petteri
