### ISSUE TITLE
X-Road Setup and configuration step by step

### ISSUE THREAD

**Issue by raselmeya94** [nordic-institute/X-Road#1869]
I believe that X-Road is an immersive and valuable tool for contemporary technology and organizational use. For those who wish to learn about or contribute to the further improvement of X-Road, it is crucial to first gain a proper understanding of its workings and the setup and configuration procedures. This is why I suggest creating a document that outlines the step-by-step process from the beginning to successfully demonstrating file sharing. While I am aware that there are already existing documents available, for new developers, it can be challenging to discern where to start. If anyone is willing to help or provide a comprehensive guide for setting up the file-sharing procedure, including links to relevant documentation and detailed steps, it would be highly beneficial.

for example, 
step 1: Environment
step 2: git clone or docker image pull
step 3: start Configuring
      ..
      ..
      ..
step N: Successful file sharing is done.

**Comment by petkivim** [comment]
Hi @raselmeya94! The best way to get started with X-Road is the X-Road Fundamentals training in the X-Road Academy:

https://academy.x-road.global/courses/x-road-fundamentals

The training requires registration, but it's free of charge. Also, there are other free trainings targeted for X-Road users based on the role: Security Server administrator, Central Server administrator, X-Road service developer and X-Road core developer. After completing the X-Road Fundamentals training, it's recommended to complete additional training(s) according to your role.

Here's a quick guide to get started with setting up your own X-Road environment:

1. [Install X-Road](https://github.com/nordic-institute/X-Road/tree/develop/ansible#3-install-x-road-using-ansible)
2. [Configure the environment](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0)
3. [Test that everything is working](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4915774/How+to+Test+That+the+Security+Server+Is+Working+After+Completing+Installation+and+Configuration)

**Comment by petkivim** [comment]
Also, you might want to look at the X-Road Playground as well. It's a public X-Road test environment with a couple of test services that you can use the get more familiar with X-Road:

https://x-road.global/xroad-playground

**Comment by raselmeya94** [comment]
Thanks @petkivim.
I will trying to follow your instructions
