### ISSUE TITLE
X-road issue with building containers (ansible)

### ISSUE THREAD

**Issue by rokas0504** [nordic-institute/X-Road#1880]
Hello,
I am trying to make a containers following this tutorial: https://www.youtube.com/watch?v=RV-Dq69yFVE&list=PL1hmZln4PWNWjy-7aCYrdr6yo3NDOvrT9&ab_channel=NordicInstituteforInteroperabilitySolutions
It is the same tutorial as the ansible README.txt.
But when I try to run "ansible-playbook -i hosts/demo_hosts.txt xroad_init.yml"  it always fails with the error: 
fatal: [xroad-lxd-cs]: FAILED! => {"changed": false, "msg": "No package matching 'xroad-centralserver' is available"}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
xroad-lxd-cs               : ok=14   changed=2    unreachable=0    failed=1    skipped=7    rescued=0    ignored=0   
xroad-lxd-ss1              : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
xroad-lxd-ss2              : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

Do you have any idea what could cause this? Using Ubuntu 22.04.3 version with a parallels vm.

**Comment by petkivim** [comment]
Hi @rokas0504! What processor architecture your host is using (ARM or x86)? Currently, the X-Road release packages don't support ARM which is why they cannot be installed on an ARM host.

**Comment by raits** [comment]
Closing this issue since it is inactive.
