### ISSUE TITLE
Unable to connect to the OCSP responder

### ISSUE THREAD

**Issue by thanhtung6824** [nordic-institute/X-Road#189]
Hi everyone,
I'm a newbie in X-Road. I'm trying to build a x-road system follow https://www.youtube.com/watch?v=RV-Dq69yFVE&t=1372s

In step 3.5 of this document 
https://confluence.niis.org/pages/viewpage.action?pageId=6783483#HowtoConfigureCentralServer?-2.InstallingtheSecurityServerformanagementservices
I can't registration request. I get this error: "Failed to register cerificate"
When I check Diagnostics. OCSP Responders show:
![image](https://user-images.githubusercontent.com/28278313/64412128-eec5a180-d0b8-11e9-86c9-191dcc51d41b.png)
How can I fix this error?
Please help me. Thank in advance

**Comment by petkivim** [comment]
Hi @thanhtung6824 

The Security Server is not able to connect to the OCSP responder. The most likely reason for that is that the OCSP responder URL is incorrect. Try to update the OCSP responder URL on the Central Server using the Central Server host or IP in the OCSP responder URL (the port must be 8888), e.g.:

http://test-ca.lxd:8888 => http://demo-cs.lxd:8888

The default configuration created by Ansible has changed after the video was recorded. Back then the test CA was installed in a separate LXD container, but nowadays it's installed in the same container with the Central Server.

Best regards,
Petteri

**Comment by thanhtung6824** [comment]
Hi @petkivim 
Thank you. It worked.
