### ISSUE TITLE
TLS certificate does not match any IS certificates

### ISSUE THREAD

**Issue by kadyrkulovr** [nordic-institute/X-Road#1935]
I receive an error message: 
`<faultstring>Client (SUBSYSTEM:central-server/COM/60000054/creditinfo-subsystem) TLS certificate does not match any IS certificates</faultstring>`

I would like to correctly configure the HTTPS protocol. The documentation says that internal TLS certificates must be created for the information system server(s) and uploaded to the Security Server.

I have attempted to upload the PFX certificate (exported IS server certificate), following the prescribed steps. However, the process resulted in the following error: Invalid certificate ID: 11adafdf5a7b434d
![invalid-certificate](https://github.com/nordic-institute/X-Road/assets/6756259/d185dfde-5934-4949-91cc-acaeaa681caa)

With HTTP it works fine, but is not recommended.

Please provide any guidance on how to resolve this issue. 

**Environment Details**
X-Road  7.2.2

**Comment by petkivim** [comment]
Hi @kadyrkulovr! The information system certificate that's uploaded to the Security Server must be in `pem` or `der` format. The PFX format is probably the reason for the error.

**Comment by kadyrkulovr** [comment]
Hi @petkivim 
I use this command to extract the `.pem` format from `.pfx`:
`openssl pkcs12 -in myCertificate.pfx -out myCertificate.pem -nodes`

Same error with `.pem` format: Invalid certificate. 
Where can I see the detailed logs about this error?

**Comment by kadyrkulovr** [comment]
@petkivim 
The `.der` format is working.
Thank you very much.
