### ISSUE TITLE
Asking Help why the Security server has no valid authentication certificate

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#196]
Dear @petkivim ,

I have tried to access it via the Postman, but it is error.  Maybe because my Authentication Certificate is not valid. Because my Key Usage has only: Digital Signature, Key Encipherment, Data Encipherment.

But the Key Usage in FI it required: Digital Signature, Key Encipherment, and Data Encipherment.

Could I modify the Key Usage in the Certificate Profile?

![image](https://user-images.githubusercontent.com/8038324/64902744-1fb85e80-d6d7-11e9-9d6b-33d9e09e3d17.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The error should not be caused by the fields included/not included in the certificate. It's most likely caused by an invalid or missing OCSP response. Have you checked `/var/log/xroad/proxy.log` and `/var/log/xroad/signer.log` for details? 

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
Yes it is error like you said. Thanks I will check it

![image](https://user-images.githubusercontent.com/8038324/64903474-1255a100-d6e4-11e9-8cb3-16315e77ebe1.png)

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,
I have tried to configure the OCSP already. but it still not work.

![image](https://user-images.githubusercontent.com/8038324/64903619-9f99f500-d6e6-11e9-8f88-bf329ad6f724.png)

![image](https://user-images.githubusercontent.com/8038324/64903630-c0624a80-d6e6-11e9-9911-c818f0aad154.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Yes, you have configured OCSP responder and the diagnostics page shows that the Security Server is able to establish a network connection to the OCSP responder. However, the diagnostics feature does not test whether the OCSP responder provides valid OCSP responses on application level, it only tests the connection on network level.

Currently your OCSP responder returns [HTTP error code 500](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_errors) which indicates that for some reason it is not able to process OCSP requests. Please check the OCSP responder's log files for details.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
It works now. Thanks you so much.

![image](https://user-images.githubusercontent.com/8038324/64906704-008bf200-d714-11e9-8555-0eda3860cd75.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Excellent! You're welcome.

Best regards,
Petteri

**Comment by jpalo** [comment]
Just would like to comment here that after renewing the Server Authentication Key and after you Activate it on the Security server, it takes up to 60 mins before server checks the Activated cert. 
![image](https://github.com/nordic-institute/X-Road/assets/6917905/9e3c7450-26dc-48f8-90d6-40767a5b949b)

Until it executes the check, everything is green on the Security server portal (including diagnostics), yet API endpoints will fail with `Security server has no valid authentication certificate`.

**Comment by petkivim** [comment]
You can check the authentication certificate OCSP status on the Keys and Certificates -> SIGN and AUTH keys page:

![Screenshot 2023-06-01 at 14 37 08](https://github.com/nordic-institute/X-Road/assets/575897/4087b792-f52e-426c-b39a-96d545c755fb)

The OCSP status on the diagnostics page is green, because the connection to the OCSP service is working normally. The problem is that the OCSP response of the authentication certificate just hasn't been fetched yet. However, it's possible to force fetching the OCSP response by [emptying the OCSP cache](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4916758/How+to+Empty+the+OCSP+Cache+on+the+Security+Server).

**Comment by KarenFlora1** [comment]
Hi, I'm starting in Xroad and I'm applying a the standalone security server concept using a tutorial, https://github.com/digitaliceland/Straumurinn/blob/master/DOC/Manuals/standalone_security_server_tutorial.md. I'm in the part where I have to connect to the web service (We will start by connecting to the ping service). I have been facing the exact same problem I think, which says that {"type":"Server.ClientProxy.SslAuthenticationFailed","message":"Security server has no valid authentication certificate","detail":"17625285-e412-40c4-9771-ce8c83545c38
![gitii](https://github.com/user-attachments/assets/fc1358f1-3375-44e8-bee5-63b83a2d5c44)
I would like to hear from you
Best Regards,
Karen Flora

**Comment by petkivim** [comment]
Hi @KarenFlora1! What version number of the Standalone Security Server are you using? Based on the screenshot it's a very old version that's not supposed to work anymore. Please try with the latest version `noble-7.5.1`:

```
docker run -p 127.0.0.1:4000:4000 -p 127.0.0.1:8080:8080 -d --name standalone --hostname ss niis/xroad-security-server-standalone:noble-7.5.1
```

**Comment by KarenFlora1** [comment]
Hi @petkivim, Thank you very much, the tutorial is using an old version, its 6.25.0. I used the one you passed and I was able to finish the tutorial. But when I enter in the Diagnostics section I still see a lot red, I would like to know if it's normal?
![N_xroad](https://github.com/user-attachments/assets/74dca2ca-2a60-4d06-90ed-7dc5a5723aa4)
![N_xroad1](https://github.com/user-attachments/assets/0f8b7f3f-c46c-4f04-845e-071f22736dd1)
![N_xroad2](https://github.com/user-attachments/assets/cd08d1d4-d3d3-4f58-8c75-90bae80cc6f0)
And I would like to know if there are more tutorials that I could use to learn more about Standalone Security server.
Best regards,
Karen Flora

**Comment by petkivim** [comment]
Hi @KarenFlora1! Having the red sections in the Diagnostics page is completely normal with the Standalone Security Server so there's no need to worry about those. The reason for them is that the Security Server requires a connection to the Central Server, OCSP service and timestamping service to operate normally. However, the Standalone Security Server is a special version of the Security Server that provides a limited functionality without requiring any additional components.

[X-Road Academy](https://academy.x-road.global/) provides free online training courses for different X-Road user roles. The courses are more theoretical and they give you an excellent basis to get started with X-Road.

**Comment by KarenFlora1** [comment]
Hi @petkivim! Thank you for the explanation, it makes sense now.
I started from the X-Road courses. I did 3 of them and was in the service developer course where I heard about the standalone security server, cause I wanted to configure 2 security servers (I only configured one) and a central server in Ubuntu machines but the lack of resources made me search for this solution. On the other hand, my colleagues who configured have be facing this problem:
![xroad3](https://github.com/user-attachments/assets/410894d0-146b-444b-8717-82cbb90d2c48) 
Tell me if you need more details

Best regards,
Karen Flora

**Comment by petkivim** [comment]
After uploading the configuration anchor to the Security Server, the Security Server tries to download internal configuration from the Central Server.  Based on the error message, the verification of the downloaded internal configuration fails for some reason. You should check the `/var/log/xroad/configuration_client.log` log file for more details about the problem.
