### ISSUE TITLE
Automation for register new member

### ISSUE THREAD

**Issue by thanhtung6824** [nordic-institute/X-Road#200]
Hi everyone.
I want write a API gate way for automation task in X-Road. Example: I want write API create new member of X-Road and register security server, ....
Is this possible? Thank in advance

**Comment by petkivim** [comment]
Hi @thanhtung6824 

The present version of Security Server does not provide an API for automating different administration and configuration tasks. However, we're currently implementing such an API and it will be released in 2020. The current version of the API description can be found [here](https://github.com/nordic-institute/X-Road-REST-UI/blob/develop/src/proxy-ui-api/src/main/resources/openapi-definition.yaml).

Best regards,
Petteri

**Comment by thanhtung6824** [comment]
Hi @petkivim
What about API of Center server? Such as: adding new client for Center server 
Thanks

**Comment by petkivim** [comment]
Hi @thanhtung6824

A management API for Central Server will be implemented next, once the Security Server API has been completed. The API will provide access to all features that are available through the UI.

Best regards, 
Petteri

**Comment by thanhtung6824** [comment]
Thanks you
