### ISSUE TITLE
OCSP nextUpdate is too old

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#207]
Dear @petkivim ,
May I ask you about this error? 
![image](https://user-images.githubusercontent.com/8038324/65931356-8f4a7f80-e433-11e9-8c75-4496430a4734.png)

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

By default, the Security Server validates the value of `nextUpdate` field in the OCSP response, and it is required that the value is not older than `atDate`. However, it is possible to disable verification of the `nextUpdate` value which means that an OCSP response containing an older value is accepted as well. Instructions can be found [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#161-verify-next-update).

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could you tell me the exact directory of Central Server or Security Server to change it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Dear @darapenhchet 

You should upload the configuration file to the Central Server:

<img width="1602" alt="Screenshot 2019-10-01 at 10 54 36" src="https://user-images.githubusercontent.com/575897/65944266-f9feb980-e439-11e9-81ce-2a5387cd1149.png">

Select `nextupdate-params.xml` Under Configuration Parts and upload the configuration file that you have created according to the instructions included in my previous response.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
Thanks you for your helping.

Best Regards,
Dara Penhchet
