### ISSUE TITLE
Asking how to download the File in XRoad by using the Rest API?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#209]
Dear @petkivim ,

Could I ask you about the File Access Control with XRoad Solution? Could you share me about the solution how to control and access the files?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

I'm sorry, but I'm not sure if I understand the question. Could you please describe in more detail what files do you mean? Would you like to transfer files over X-Road, access the messagelog archive files or something else maybe?

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I mean I want to transfer files over X-Road both upload and download.

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Have you taken a look at [X-Road File Service](https://github.com/vrk-kpa/xroad-fileservice) -  a sample web service for transferring files over X-Road. The application uses X-Road's SOAP interface.

Another alternative is to use X-Road's REST interface which supports transferring any kind of content over HTTP. Using the REST interface you could use a multipart message or include a `base64` encoded binary data in JSON/XML message.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
Thank you so much

Best Regards, 
Dara Penhchet
