### ISSUE TITLE
The configuration anchor

### ISSUE THREAD

**Issue by asow25** [nordic-institute/X-Road#2148]
Hello, I discovered the solution a few days ago and followed the training on YouTube, which was wonderful!
The Ansible script deserves credit; it's excellent work!
I completed an installation, launched the Security Server UI console, and it asked me: ```Import the configuration anchor provided by the Central Server's administrator.```

Please tell me where I can locate it.

**Comment by petkivim** [comment]
Hi @asow25! It's nice to hear that you have found the available resources useful. 😄

Are you deploying a single Security Server or an entire X-Road environment? In the latter case (entire X-Road environment), please follow [this configuration guide](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0). Instead, in the first case (single Security Server), please complete only the steps 3.1-3.6 of the configuration guide.

**Comment by asow25** [comment]
How to access Central Server's admin interface?
Port 4000 is not listening on the central server.

**Comment by petkivim** [comment]
Did you try with `https://<CENTRAL_SERVER_ADDRESS>:4000`? The Central Server admin interface only supports `https` and `http` is no supported. If that's not the cause of the issue, please see the Central Server [post-installation checks](https://docs.x-road.global/Manuals/ig-cs_x-road_6_central_server_installation_guide.html#212-post-installation-checks).

**Comment by asow25** [comment]
```
root@xroad-cs:~# sudo systemctl list-units "xroad*"
  UNIT                 LOAD   ACTIVE SUB     DESCRIPTION          
  xroad-base.service   loaded active exited  X-Road initialization
  xroad-signer.service loaded active running X-Road signer

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
root@xroad-cs:~# 
root@xroad-cs:~# 
root@xroad-cs:~# dpkg -l | grep xroad
ii  xroad-base                        7.4.2-1.ubuntu22.04                     amd64        X-Road base components
rc  xroad-center                      7.4.2-1.ubuntu22.04                     all          X-Road central server
rc  xroad-center-management-service   7.4.2-1.ubuntu22.04                     all          X-Road Central Server Management Service
rc  xroad-center-registration-service 7.4.2-1.ubuntu22.04                     all          X-Road Central Server Registration Service
rc  xroad-centralserver-monitoring    7.4.2-1.ubuntu22.04                     all          Monitoring client configuration for X-Road central
ii  xroad-confclient                  7.4.2-1.ubuntu22.04                     amd64        X-Road configuration client components
ii  xroad-confproxy                   7.4.2-1.ubuntu22.04                     all          X-Road configuration proxy
ii  xroad-database-local              7.4.2-1.ubuntu22.04                     all          Meta-package for X-Road local database dependencies
ii  xroad-nginx                       7.4.2-1.ubuntu22.04                     amd64        X-Road nginx component
ii  xroad-signer                      7.4.2-1.ubuntu22.04                     amd64        X-Road signer component
root@xroad-cs:~# 
root@xroad-cs:~# 
root@xroad-cs:~# telnet localhost 4000
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by petkivim** [comment]
It seems that some packages are missing and there's at least one extra package too. Here's how the package list should look like:

```bash
root@test-cs:~# dpkg -l | grep xroad
ii  xroad-base                         7.4.2-1.ubuntu22.04 amd64        X-Road base components
ii  xroad-center                       7.4.2-1.ubuntu22.04 all          X-Road central server
ii  xroad-center-management-service    7.4.2-1.ubuntu22.04 all          X-Road Central Server Management Service
ii  xroad-center-registration-service  7.4.2-1.ubuntu22.04 all          X-Road Central Server Registration Service
ii  xroad-centralserver                7.4.2-1.ubuntu22.04 all          X-Road central server
ii  xroad-centralserver-monitoring     7.4.2-1.ubuntu22.04 all          Monitoring client configuration for X-Road central
ii  xroad-confclient                   7.4.2-1.ubuntu22.04 amd64        X-Road configuration client components
ii  xroad-database-local              7.4.2-1.ubuntu22.04 all          Meta-package for X-Road remote database dependencies
ii  xroad-nginx                        7.4.2-1.ubuntu22.04 amd64        X-Road nginx component
ii  xroad-signer                       7.4.2-1.ubuntu22.04 amd64        X-Road signer component
```

Could you share the Ansible hosts file that you used in the installation? It seems that you have tried to install the Configuration Proxy component on the same host with the Central Server. However, they must be run on separate hosts. Also, the Configuration Proxy is an optional component that you can skip.

**Comment by asow25** [comment]
I've got 02 machines
```
cat hosts.ini
---
[xroad:children]
cs_servers
ss_servers
cp_servers
ca_servers

#central servers
[cs_servers]
cs1.dev.veone.net ansible_host=176.31.142.247

#security servers
[ss_servers]
ss1.dev.veone.net ansible_host=176.31.142.248

#configuration proxies
#[cp_servers]
#cp.dev.veone.net ansible_host=

[cp_servers:children]
cs_servers

#certification authority, time stamping authority and ocsp service server
#[ca_servers]
#ca.dev.veone.net ansible_host=

[ca_servers:children]
ss_servers

[ss_servers:vars]
variant=vanilla
```

**Comment by asow25** [comment]
I resumed, this time without the proxy.
I logged in to the dashboard and there are URLs https://<central_server_ip>/internalconf
When I open the link, there's nothing going on.

**Comment by petkivim** [comment]
So you're able to access the dashboard now. That's good news! The next step is to follow [this configuration guide](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0). The internal conf configuration data will be available only after completing the initial configuration.

**Comment by petkivim** [comment]
In order to complete the configuration, you need to have a CA with OCSP and a timestamping service. The easiest way is to use the [Test CA](https://github.com/nordic-institute/X-Road/blob/develop/ansible/TESTCA.md) and install it on the same host with the Central Server using Ansible.

```
#central servers
[cs_servers]
cs1.dev.net ansible_host=x.x.x.x

#certification authority, time stamping authority and ocsp service server
[ca_servers]
cs1.dev.net ansible_host=x.x.x.x
```

**Comment by asow25** [comment]
Hello @petkivim, I hope you are well, thank you very much! I finished the configuration and at the end, there is a test, we create a subsystem on SS and then approved on the CS and it has a registered status.

**Comment by petkivim** [comment]
1. The operational schema that you described is correct. More information about the actual data exchange flow is available [here](https://x-road.global/data-exchange).
2. Could you elaborate on what do you mean by adding SSL to the CS and SS web portal? Do you want to [replace the UI/API certificate with a certificate issued by a trusted CA](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4915640/How+to+Change+the+Security+Server+UI+API+TLS+Certificate)? More information about keys and certificates used by X-Road is available [here](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4916191/What+Kind+of+Keys+and+Certificates+the+Security+Server+Has).

Are you already familiar with the [X-Road Academy](https://x-road.thinkific.com/courses/x-road-fundamentals)? It provides several free online courses that help you to get started with X-Road.

**Comment by asow25** [comment]
Thank you for your attention, @petkivim

**Comment by asow25** [comment]
Hello, @petkivim! How are you? I took the course with the X-Road Academy, and it was incredible. Many thanks!
How do I configure TLS certificates on Central Server?

**Comment by petkivim** [comment]
Hi @asow25! That's great to hear! 😄

What TLS certificate(s) do you mean? Do you want to change 1) the admin UI/API TLS certificate (port 4000) and/or 2) the global configuration download certificate (port 443)?

Instructions to change the global configuration download certificate (2) are available [here](https://docs.x-road.global/Manuals/ig-cs_x-road_6_central_server_installation_guide.html#271-configuring-tls-certificates). Instead, you can change the admin UI/API TLS certificate (1) by following [these](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4915640/How+to+Change+the+Security+Server+UI+API+TLS+Certificate) instructions. Please note, that the instructions are for the Security Server and therefore, you must replace `proxy-ui-api` with `center-admin-service`, e.g., `/etc/xroad/ssl/proxy-ui-api.key` => `/etc/xroad/ssl/center-admin-service.key`.

**Comment by asow25** [comment]
1) the admin UI/API TLS certificate (port 4000)

To configure the central server to use a certificate issued by a trusted CA to serve global configurations via HTTPS, replace the existing certificate files (global-conf.crt) and associated private key (global-conf.key), located in the /etc/xroad/ssl/ directory.
Reload the nginx service for the certificate modification to take effect.

When I do https://<cs_uri>, I get **403 Forbidden** but my ssl is displayed, but I do https://<cs_uri>:4000, xroad-admin ui is displayed but without my ssl, rather openssl generated during deployment

**Comment by petkivim** [comment]
In theory, changing the port is possible, but it requires changes to multiple places and the process is not documented. Therefore, I don't recommend changing it.

**Comment by asow25** [comment]
I realise... On the Security Server, I had this error ```Edit Security Server Address``` :
```
AxiosError: Request failed with status code 500
```

**Comment by petkivim** [comment]
Yes, those are consequences of changing the port. To get rid of them, you should modify the source code, build your own installation packages and do the installation using your own packages.

**Comment by asow25** [comment]
I have not changed ports.
I enabled SSL on global-conf, proxy-ui-api, and center-admin-service. For Central Server, I used fqdn as the name instead of IP address.

**Comment by petkivim** [comment]
Indeed, the second error message is related to the certificate path. In that case, you should review the instructions and double check that you've completed all the steps according to them. In step 12 on the Central Server, you must restart the `xroad-center` service. The related log file is `/var/log/xroad/centralserver-admin-service.log`.

**Comment by asow25** [comment]
tail -f /var/log/xroad/proxy_ui_api.log

2024-05-27T17:48:31.647Z [https-jsse-nio-4000-exec-4] correlation-id:[6654c76f04902fece9c6b1782df231ac] INFO  ee.ria.xroad.common.AuditLogger - {"event":"Edit security server address failed","user":"xadmin","ipaddress":"<MY_INTERNET_ROUTER_IP_ADDRESS>","reason":"Cannot invoke \"String.equals(Object)\" because the return value of \"org.niis.xroad.securityserver.restapi.service.GlobalConfService.getSecurityServerAddress(ee.ria.xroad.common.identifier.SecurityServerId)\" is null","warning":false,"auth":"Session","url":"/api/v1/system/server-address","data":{"address":"<SECURITY_SERVER_URI>"}}
2024-05-27T17:48:31.648Z [https-jsse-nio-4000-exec-4] correlation-id:[6654c76f04902fece9c6b1782df231ac] ERROR o.n.x.r.e.ApplicationExceptionHandler - exception caught
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.niis.xroad.securityserver.restapi.service.GlobalConfService.getSecurityServerAddress(ee.ria.xroad.common.identifier.SecurityServerId)" is null
	at org.niis.xroad.securitys

**Comment by petkivim** [comment]
Unfortunately, the error message doesn't include the root cause of the problem - only that there's something wrong with your configuration. Could you share the whole `/var/log/xroad/proxy_ui_api.log` and `/var/log/xroad/configuration_client.log` log files?

**Comment by asow25** [comment]
I have removed the SSL certificates I had added, and it works. I was able to configure:
  - cs :
    - center-admin-service
    - global-conf
  - ss :
    - proxy_ui_api
    
With Ansible, we deploy the certification authority. Is my approach correct? To have two types of SSL certificates (short-term), one for web display and another (long-term) for communication between X-Road services?
Also, should I use FQDN to rename the services or use IP addresses?

**Comment by petkivim** [comment]
The CA that you deploy with Ansible is meant for issuing authentication certificates for Security Servers and sign certificates for X-Road members. Using that CA for the UI and global configuration certificates doesn't bring any additional value. Instead, if you want to replace the self-signed UI and global conf certificates created during the installation process, you should use some commonly trusted CA.

In general, it's recommended to use FQDN in certificates.
