### ISSUE TITLE
Where data encryption is done in X-ROAD

### ISSUE THREAD

**Issue by majana1** [nordic-institute/X-Road#2162]
Hi, I beg a clarification,
In reading of X-Road documentations, I am not clear with the following

Data from one institution to another via X-Road goes from Security Server->Central Server->Security server. Where is encryption being done? Is it the requirment of client and sender's system to make encryption?

Are there any direct connection between security servers? Or all communications pass through Central Server? In network language, can one Security server make a PING to another security server?
Please I beg your understanding

**Comment by petkivim** [comment]
Hi @majana1! More information about the X-Road data exchange flow is available [here](https://x-road.global/data-exchange). The page includes answers to your questions.

Are you familiar with the [X-Road Academy](https://academy.x-road.global/)? The Academy provides free online courses to get started with X-Road. It's strongly recommended to start with the [X-Road Fundamentals](https://academy.x-road.global/courses/x-road-fundamentals) course.

**Comment by raits** [comment]
Closing this issue since it is inactive.
