### ISSUE TITLE
X-Road Logo is on MIT license?

### ISSUE THREAD

**Issue by gagarine** [nordic-institute/X-Road#220]
You released the logo with the source code: https://github.com/nordic-institute/X-Road/blob/develop/xroad_logo_small.png

Is that correct? Can you publish a SVG version? I will add it on https://en.wikipedia.org/wiki/X-Road

**Comment by petkivim** [comment]
Hi @gagarine 

The MIT license is an open source software license that covers the X-Road source code. X-Road name and logo instead are registered trademarks of the Estonian Information System Authority (RIA) and therefore, using them is forbidden without a permission of the trademark owner. NIIS is responsible for sublicencing the trademark.

However the use of X-Road trademark in a truthful manner to refer accurately to X-Road has been usually allowed. Therefore, it’s allowed i.e. to use the X-Road logo in the X-Road Wikipedia article.

Best regards,
Petteri

**Comment by gagarine** [comment]
Hi @petkivim. Thanks you for those precision, that make sens. Do you have the logo in SVG format?

**Comment by petkivim** [comment]
We have not published the logo in `SVG` format so please use the `PNG` version.
