### ISSUE TITLE
[ansible] Central Server script doesn't work on Ubuntu 18.04 Minimal  

### ISSUE THREAD

**Issue by nanndoj** [nordic-institute/X-Road#232]
The ansible script for setting up the central server is failing when installing on a Minimal version of Ubuntu 18.04 (ubuntu-minimal-1804-bionic). This is because the `locales` package is not installed by default in this image. 

One possible solution is to ensure that the `locales` is installed on the `xroad-base` script as described in https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md#24-preparing-os

### Steps to reproduce
Run the playbook `xroad_init.yml` on a minimal version of Ubuntu 18.04 bionic.

### Expected results
The script should run without any problems.

### Actual results
The script fails with the following error
```
failed: [xx.xx.xx.xxx] (item=en_US.UTF-8) => {"ansible_loop_var": "item", "changed": false, "item": "en_US.UTF-8", "msg": "/etc/locale.gen and /var/lib/locales/supported.d/local are missing. Is the package \"locales\" installed?"}
```

**Comment by petkivim** [comment]
Your open PR (#187) seems to contain a fix to the problem. There's an issue about evaluating and approving the PR in our backlog so it has not been forgotten.

https://jira.niis.org/browse/XRDDEV-712

As a workaround it's also possible to install the missing package manually before running the Ansible script.

Best regards,
Petteri
