### ISSUE TITLE
Asking about the Central Monitoring Server?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#237]
Dear XRoad,

Where could I install the Central Monitoring Server on XRoad?

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Dear @darapenhchet 

Do you mean the operational monitoring component that is used to collect and publish operational monitoring data centrally? It can be found here:

https://github.com/ria-ee/X-Road-opmonitor

Please note that the component is maintained by the Estonian Information Systems Authority (RIA) and not by NIIS.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear petkivim,
Thanks you so much,
