### ISSUE TITLE
Failed to build containers

### ISSUE THREAD

**Issue by doriavatin** [nordic-institute/X-Road#239]
Hello, I am using Ubuntu 18.04 LTS and tried to build new containers after reinstalling X-Road two times and this error showed up:

xroad2019@xroad2019-TERRA-PC:~/X-Road/ansible$ sudo ansible-playbook -i hosts/lxd_hosts.txt xroad_init.yml 
[sudo] password for xroad2019: 
 [WARNING]:  * Failed to parse /home/xroad2019/X-Road/ansible/hosts/lxd_hosts.txt with ini plugin: /home/xroad2019/X-Road/ansible/hosts/lxd_hosts.txt:41: Section [demo-servers:children] includes
undefined group: cs-servers

 [WARNING]: Unable to parse /home/xroad2019/X-Road/ansible/hosts/lxd_hosts.txt as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [lxd_servers] *****************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [init-lxd : Ready all Ubuntu bionic containers] *******************************************************************************************************************************************************

TASK [init-lxd : Ready all CentOS 7 containers] ************************************************************************************************************************************************************

TASK [init-lxd : Install Python2 in container if necessary] ************************************************************************************************************************************************

PLAY [ss_servers] ******************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
fatal: [demo-ss1]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1573233580.12-4287626158680 `\" && echo ansible-tmp-1573233580.12-4287626158680=\"` echo ~/.ansible/tmp/ansible-tmp-1573233580.12-4287626158680 `\" ), exited with result 1", "unreachable": true}
fatal: [demo-ss2]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1573233580.13-97301733296530 `\" && echo ansible-tmp-1573233580.13-97301733296530=\"` echo ~/.ansible/tmp/ansible-tmp-1573233580.13-97301733296530 `\" ), exited with result 1", "unreachable": true}

NO MORE HOSTS LEFT *****************************************************************************************************************************************************************************************
	to retry, use: --limit @/home/xroad2019/X-Road/ansible/xroad_init.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
demo-ss1                   : ok=0    changed=0    unreachable=1    failed=0   
demo-ss2                   : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

Help would be appreciated.
Thanks in advance.

**Comment by petkivim** [comment]
Hi @doriavatin 

Using the current develop branch, the given command `sudo ansible-playbook -i hosts/lxd_hosts.txt xroad_init.yml` works without problems. Although sudo shouldn't be needed in normal case.

Could you please provide the contents of your `lxd_hosts.txt` file? The problem is most likely caused by invalid configuration.

Best regards,
Petteri
