### ISSUE TITLE
Asking about the OCSP?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#242]
Dear XRoad,

Should we put the SubCA's OCSP or RootCA's OCSP?

![image](https://user-images.githubusercontent.com/8038324/68601088-3f50e500-04d6-11ea-94ec-bb7600a53caa.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

You should configure both. OCSP responses of the AUTH/SIGN certificates are fetched from the sub CA's OCSP service, and OCSP responses of the sub CA's certificate are fetched from the root CA's OCSP service.

In case you configure the sub CA as a root CA, and omit the root CA in the configuration, it's enough to add the sub CA's OCSP service.

Best regards,
Petteri
