### ISSUE TITLE
Asking about the Operational Monitoring?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#256]
Dear XRoad, 

I have a problem with Operational Monistoring  it said Unknown service: **getSecurityServerOperationalData**

2019-11-18 10:00:03,163 [qtp1031968647-43] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error
ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.UnknownService: Unknown service: SERVICE:CAM/GOV/201903/getSecurityServerOperationalData

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Have you installed the `xroad-addon-opmonitoring` package on the Security Server?

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
We have to install it on all security servers right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet

The package must be installed on all Security Servers where the operational monitoring data is collected.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I install it and it show this message

![image](https://user-images.githubusercontent.com/8038324/69034450-d3113c80-0a13-11ea-8f93-29f61c9feb56.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Have you checked that the `xroad-opmonitor` service is running?

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
It shows like this.
![image](https://user-images.githubusercontent.com/8038324/69035116-6c8d1e00-0a15-11ea-8a21-4725bcfbe042.png)
Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Did you use the SOAP or REST interface to invoke the service? It is available through the SOAP interface only, REST is not supported currently.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I am using the REST Serviece nowadays.

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

That's the reason for the error message. Operation monitoring services can be invoked using the SOAP interface only. The operation monitoring protocol description can be found at:

https://github.com/nordic-institute/X-Road/blob/develop/doc/OperationalMonitoring/Protocols/pr-opmon_x-road_operational_monitoring_protocol_Y-1096-2.md

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
So it means if I use the REST API, then I cannot use the Operation Monitoring to monitor the request between the Consumer Security and Provider Security Server right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

You can use the REST API to exchange data between service consumers and service providers. All the requests are recorded by the operational monitoring component - both REST and SOAP requests. Instead, the operational monitoring data stored by the Security Server can be accessed through the SOAP and JMX interfaces, but not through the REST interface.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

After I installed the `xroad-addon-opmonitoring`. Right now I can collect that log records.

Thanks you for your help.
Best Regards,
Dara Penhchet

**Comment by zemdem** [comment]
Hi,
I have an issue retrieving service calls stats. 
Only metadata services stats (getSecurityServerOperationalData) are collected. All the rows in the databases have "clientSubsystemCode" as MONITORING and "serviceCode" as getSecurityServerOperationalData. I have no metrics of my real service calls. 
Any idea ? 

Thanks and regards
