### ISSUE TITLE
Can not connet to OCSP

### ISSUE THREAD

**Issue by nguyenhabkit** [nordic-institute/X-Road#284]
Hi @petkivim ,
I setup the Xroad Test CA is ok, but I can't connect to ocsp from SS server like this:
![image](https://user-images.githubusercontent.com/37961023/70204822-8daf7780-1754-11ea-927d-baae2e1b0d9e.png)
By the way, I check ocsp an tsa status is running:
![image](https://user-images.githubusercontent.com/37961023/70204885-b9caf880-1754-11ea-8872-75e14184e057.png)
and telnet from ss server to port 8888 and 8899 is ok.
I can't understand the above error. Please help me!
Thank you,
Nguyen Ha.

**Comment by venkatesh-1986p** [comment]
Hi @nguyenhabkit,

Check the permission of the pem files.

**Comment by nguyenhabkit** [comment]
hi @petkivim ,
this is permission of the pem files
![image](https://user-images.githubusercontent.com/37961023/70207054-1f6eb300-175c-11ea-9b8c-93b666d4ecb3.png)
 What should I grant for them?

**Comment by venkatesh-1986p** [comment]
Run the ocsp in root user.

Thanks & Regards,
Venkatesh Pendlikal

**Comment by nguyenhabkit** [comment]
I use sudo to run service :  sudo systemctl start ocsp. But the result still like this:
![image](https://user-images.githubusercontent.com/37961023/70207769-46c67f80-175e-11ea-9bf2-20267ec269be.png)

**Comment by nguyenhabkit** [comment]
Thank you so much for your help @venkatesh-1986p. I resolved the error by granting read privilege to *.pem for other user

Thank you,
Nguyen Ha.
