### ISSUE TITLE
bulk creation of  members

### ISSUE THREAD

**Issue by egobsv** [nordic-institute/X-Road#286]
We have a few hundred organizations that can potentially join our X-Road installation. Aside from creating them individually using the central server UI, is there a way to load members directly into the database?  

Thanks for your help,
Eric.

**Comment by petkivim** [comment]
Hi,

At the moment Central Server does provide a feature that enables bulk creation of members. The only officially supported way is to create them manually using the UI. 

However, it is possible to create a script that reads new member data from a file and creates new member records directly in the Central Server database. Creating such a script requires studying the Central Server [data model](https://github.com/nordic-institute/X-Road/blob/develop/doc/DataModels/dm-cs_x-road_central_server_configuration_data_model.md#18-entity-relationship-diagram). 

Best regards,
Petteri

**Comment by egobsv** [comment]
Thank you for your guidance, I was able to add doing a bulk insert into the security_server_clients table. 
Regards,
