### ISSUE TITLE
X-Road support for "Mobile ID"

### ISSUE THREAD

**Issue by cyberphone** [nordic-institute/X-Road#3]
Hi X-Roaders,
I just wanted to hear if there is any interest in providing client authentication support into X-Road.

FWIW, I'm currently implementing a mobile authentication client which you can play with in a Web mock-up: https://cyberphone.github.io/doc/mobile-id/ui-demo/

It is based on the same platform as: https://test.webpki.org/webpay-merchant/home

Anders

**Comment by cyberphone** [comment]
Hi @petkivim I believe we are talking about different "clients" here.  I'm talking about users authenticating to Web portals which in turn talk to X-Road services.  Estonia seem to use a whole bunch of different login methods: https://www.emta.ee/eng/emta_login/nojs

The project I'm working with is comparable to an open version of Smart-ID although the technical underpinnings are quite different (TEE versus server-shared keys).

**Comment by petkivim** [comment]
Hi @cyberphone,

In Estonia a person has one digital identity and multiple authentication methods. You can always access the same information despite the authentication method you use. In this way everyone can choose a method that work the best for them. Finland has the same approach and their authentication solution is available on [GitHub](https://github.com/vrk-kpa?utf8=%E2%9C%93&q=e-identification&type=&language=).

Yes, using X-Road as a data exchange layer between a web portal and various data sources is a very common use case. The role of X-Road in that case is to provide a secure communication layer between information systems and authenticate the message exchange parties on machine-to-machine level.

The web portal is responsible for authenticating the end user and the web portal is also free to decide which authentication methods it provides to its users. X-Road does not check or verify the end user's identity or authentication in any way - the web portal is responsible for that. When the web portal makes a query to an external data source over X-Road, a unique identifier (e.g. personal code, social security number etc.) identifying the authenticated user is used as a request parameter. In addition, an authentication token or session context can be included in the request message, but then the data source is responsible for verifying it. However, it is not a common practice to do so.

X-Road is a data exchange layer between information systems and it does not validate the message content, except SOAP headers that are used for message processing.

**Comment by cyberphone** [comment]
Hi @petkivim I fully understand this.  My question was simply if there could be an interest in adding a (hopefully) universal applicable mobile client to the X-Road project as a sub project.  I could not find any counterpart in the GitHub link you provided but maybe I didn't look close enough :-)

**Comment by petkivim** [comment]
Hi @cyberphone 

At the moment we're concentrating on the X-Road project and currently there are no plans to take new sub projects. Finland's Population Register Centre that's the provider of Suomi.fi services would be the right counterpart in this case. Their contact information can be found at:

https://esuomi.fi/contact-information/?lang=en

On the Estonian side the right counterpart is the Estonian Information System Authority:

https://www.ria.ee/ee/pki-kontakt.html

**Comment by JyrgenSuvalov** [comment]
Hi @cyberphone 

Like Petteri said, in Estonia most of our X-Road connected information systems already use mobile-ID and ID-card authentication. ID-cards are mandatory for Estonian citizens and mobile-ID is widely used as well.

Information about our ID-card and mobile-ID can be found here: https://www.id.ee/?lang=en. You can find our eID team's contact information from Petteri's link.
We also have some open source solutions for integration with our national eID available on [GitHub](https://github.com/e-gov) under the TARA-* repositories. Unfortunately, a lot of it is in Estonian at the moment.

In Estonia, we have played around with the idea of adding ID-card and mobile-ID authentication support to the Security Server web interface, but since the Security Server management web interface is typically not made accessible from the public internet, it would probably be overkill.

**Comment by cyberphone** [comment]
Hi @JyrgenSuvalov @petkivim The "problem" I'm trying to solve is that many countries have outsourced issuance to _multiple_ commercial entities who all provide their unique Mobile ID solution.  This should be compared to Sweden where all banks agreed on a single App not tied to any particular bank which has been a real boon for everybody.  I'm interested in creating a similar system but OPEN and "untied" from banks and countries.  Using ID-cards on-line is something I don't see as a viable concept for the future but I know Estonia do not agree with that 😀

**Comment by petkivim** [comment]
Hi @cyberphone  It's very interesting to hear what they have achieved in Sweden - sounds very good from end users point of view. Creating a similar, open system that does not depend on banks and/or countries is a very ambitious goal.

Technically it is definitely doable as there are already many widely used authentication mechanisms available that can be used in mobile apps too, e.g. Facebook Connect, Sign In With Twitter, and OpenID Connect etc. I think that the main question is who is going to be the identity provider of the solution and how the user's identity is verified. For example, when you open a bank account you must first go to the bank, present your IDs and so on. Similarly, you must present your passport or some other official ID when you go to pick up your ID card. In the bank's case, after that you're given credentials to the bank's online system and you can use the same credentials for accessing other service provider's services too. In that case the bank acts as an identity provider that has verified your identity. The bank is a trusted identity provider and other service provider's trust the information it is providing. Therefore, there's no need to go there physically and prove your identity every time you want to open a new service. Creating a new system that does not depend on banks or countries would require a party that replaces the bank in the chain - a trusted party that verifies the identity of the users. The challenge is that the initial verification requires face-to-face contact with the user.

**Comment by cyberphone** [comment]
Pardon me @petkivim, I was probably a bit unclear.  When I referred to "untied" to banks and countries, I only meant that the "App" should be useful for any party _preferable without any modifications_ like already is the case for most FIDO alliance products.  How identity vetting is performed is out of scope for the project.  The "App" must though support different enrollment procedures including in-office.

A technical challenge which nobody (to my knowledge...) have bothered with is the fact that OOB-based authentication (Mobile +PC) usually is vulnerable to "phishing" and Mobile BankID is not an exception.

Although not a part of the project, I do keep an eye on related developments including new cool ways of enrolling mobile IDs:  https://magasin.financeinnovation.no/en/digital-legitimering-blir-fremtiden/

Anders

**Comment by petkivim** [comment]
@cyberphone, thank you for the clarification. That makes the scope much clearer. 

DNB's mobile solution for automating the initial identification process is pretty cool. I'd be happy to use a solution like that.

Petteri
