### ISSUE TITLE
Asking about the ROOT CA?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#304]
Dear @petkivim ,

For the ROOT CA do we have to provide the OCSP Responder of ROOT CA or not?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

Yes, you must configure an OCSP responder for the root CA. It is used for fetching OCSP responses for certificates issued by the root CA.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks you.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Could I

**Comment by petkivim** [comment]
Hi @darapenhchet,

Unfortunately that does not work. OCSP responder must implement the protocol defined in RFC 6960:

https://tools.ietf.org/html/rfc6960

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question? If I have a new CA Server  so could I replace my old Certificate Authority and Issue new certificate to all my Security Servers?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

Yes, that's definitely possible. It means that you must first add the new CA to your X-Road instance, generate new CSRs on all the Security Servers, sign the CSRs on the new CA and import the new certificates on all the Security Servers.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I have tried to added the new Certificate Authority in Central Server already, and I have tried to add the new certificates to the Security Server and register it, but it does not work. Do you have any solutions?

![image](https://user-images.githubusercontent.com/8038324/71656627-889f1180-2d6e-11ea-8fa5-ebbcf4ab34b9.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

Do the new certificates have valid OCSP responses available? You could try to empty the OCSP cache and see if it helps.

https://confluence.niis.org/pages/viewpage.action?pageId=17859927

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Do I need to unregister the Previous Authentication Certificate first?

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

My OCSP Response is okay.
![image](https://user-images.githubusercontent.com/8038324/71657309-e97c1900-2d71-11ea-9623-ea31b7d7faab.png)

Best Regards, 
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Or It caused by my old ocsp responder now is not working?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

The diagnostics view showing green means that the network connection between the Security Server and OCPS responder is OK - it does not mean that the OCSP responses of your certificates are OK.

What's the OCSP response status of the sign certificate in the Keys and certificates view? The error message refers to the sign certificate.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Here is the error log message,

![image](https://user-images.githubusercontent.com/8038324/71658125-5349f200-2d75-11ea-98a4-522dbefe58d6.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

Have you activated the new authentication certificate?

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
I have activated it already, but cannot register.
![image](https://user-images.githubusercontent.com/8038324/71658348-48dc2800-2d76-11ea-9819-56c3eb6b55ca.png)

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

There's something wrong with your OCSP responder - as you can see from the screenshot, the OCSP response status of all the certificates is unknown.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Do you have any solutions to solve it?

Best Regards, 
Dara Penhhcet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Unfortunately, based on the available information I don't know what is causing the problem. It seems that the network connection between the Security Server and OCSP responder is OK, but there's something wrong with the OCSP responder or the responses that it returns are not considered valid by the Security Server.

You could change the logging level of signer to `debug`/`trace` and see if it gives you more information. In addition, you (or the Certification Auhority hosting the OCSP responder) should check the OCSP responder's logs for additional information.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for you information.

Best Regards,
Dara Penhchet
