### ISSUE TITLE
TSA Configuration

### ISSUE THREAD

**Issue by GururajKulkarni2609** [nordic-institute/X-Road#305]
Hi ,
after doing the tsa configuration in Central server then sharing the anchor.xml file with the Security Server, and while doing the api request I'm getting the following error "Could not find TSP Certificate for TimeStamp" .
But I've already uploaded the TSA Certificate in Central Server

**Comment by petkivim** [comment]
Hi @GururajKulkarni2609,

Have you configured the TSA on the Security Server?

https://confluence.niis.org/pages/viewpage.action?pageId=6783483#HowtoConfigureCentralServer?-3.3Configuringthetime-stampingservice

Best regards,
Petteri

**Comment by GururajKulkarni2609** [comment]
Yes, I have configured TSA and OCSP both

**Comment by petkivim** [comment]
Have you checked the signer log (`/var/log/xroad/signer.log`) for details? You could also try to set  the signer logging level to `trace` ([instructions](https://confluence.niis.org/pages/viewpage.action?pageId=6783404)) to get more information about the problem.

Based on the error message it seems that the certificate that was used to sign the timestamp token is not available in the global configuration. When you added the TSA on the Central Server, did you add the certificate that is used to sign the timestamp tokens? Please also note that the TLS certificate of the TSA and the certificate used to sign the timestamp tokens are two different certificates. 

Regards,
Petteri
Best regards,
Petteri
