### ISSUE TITLE
Add WSDL to Security Server failed

### ISSUE THREAD

**Issue by ngolongquan** [nordic-institute/X-Road#354]
I have installed the X-road servers as below:
1. Security Server on Ubuntu 18 server
2. Rest Adapter Service on Ubuntu 16  server
When I add WSDL from Rest Adapter Service to Security Server then has failed

![restAdapterService](https://user-images.githubusercontent.com/60766273/73998345-ea692180-4993-11ea-95ac-ec5738f09847.png)

![AddWSDL](https://user-images.githubusercontent.com/60766273/73998359-f2c15c80-4993-11ea-98fe-a882dc045eca.png)

Please help me to fix it!

**Comment by petkivim** [comment]
Hi @ngolongquan! Which version of the REST Adapter Service you are using? Have you modified the WSDL or is it the version that's shipped with the component?

By the way, did you know that X-Road has a built-in REST support starting from the version 6.21.0 which means that you don't need to use the REST Adapter Service to consumer and/or produce REST services via X-Road anymore?

More information about the REST support can be found at:

- https://www.niis.org/blog/2019/3/25/two-steps-from-the-x-road-rest-support
- https://www.niis.org/blog/2019/10/6/get-some-more-rest
- https://github.com/nordic-institute/X-Road/blob/develop/doc/Protocols/pr-rest_x-road_message_protocol_for_rest.md

Regards,
Petteri

**Comment by ngolongquan** [comment]
Hi @petkivim ,
Thanks for your reply.
I'm using the url : "https://artifactory.niis.org/xroad-extensions-release-deb main" to install X-Road  Rest Adapter Service.
The url guide here: https://github.com/nordic-institute/REST-adapter-service

As you said the X-Road version 6.21.0 has a built-in REST support, my servers has installed the X-Road version 6.22.1. So, I don't need config the Rest Adapter Service right?
I have configed by following guide: https://github.com/nordic-institute/REST-adapter-service/blob/master/documentation/CRUD-API-Configuration.md

And one more question from me: Can you guide me (images/reference link) the URL to test from client to X-Road Security Server by X-Road Rest Adapter Service without OpenAPI?

(I'm a newbi of X-Road)

Regards,
Ngo Long Quan

**Comment by petkivim** [comment]
Hi @ngolongquan 

> As you said the X-Road version 6.21.0 has a built-in REST support, my servers has installed the X-Road version 6.22.1. So, I don't need config the Rest Adapter Service right?

Yes, that's right - you don't need to use the REST Adapter Service, you can use the built-in REST support instead.

There's an X-Road Academy session video available on YouTube where adding a new service and defining access rights is explained and demonstrated. After watching the video you should be able to publish a REST service via X-Road.

https://youtu.be/2maxgkPNifU

Here you can find more information about adding services and access rights:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#6-x-road-services

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#7-access-rights

Best regards,
Petteri

**Comment by ngolongquan** [comment]
Hi @petkivim 
Thanks for your answer.
I will try it.

Regards,
Ngo Long Quan

**Comment by ngolongquan** [comment]
Hi @petkivim,
Thank for you support.
I have tested the Rest Adapter Service on Security Server has succeeded
I close this issue right now.

Regards,
Ngo Long Quan
