### ISSUE TITLE
How could we remove the build date in the build package name?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#369]
Dear @petkivim ,

How could we remove the build date in the build package name?

![image](https://user-images.githubusercontent.com/8038324/74502965-f455cc00-4f21-11ea-89ba-89727bcd3ced.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The package name is defined here:

https://github.com/nordic-institute/X-Road/blob/develop/src/packages/build-deb.sh#L18

However, changing the package name is strongly discouraged. In case you decide to change it anyways, we cannot provide any support with possible issues that are related to building the packages or using the X-Road software with those packages.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could you share me the command to build the release package not include version with date?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

If you build release packages, then the date is not included in the package name:

```
./src/packages/build-deb.sh bionic -release
```

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Why the Redhat Package is not the same number of Ubuntu?

![image](https://user-images.githubusercontent.com/8038324/74511213-18240c80-4f38-11ea-9145-ba9acd1dc43b.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi  @darapenhchet 

The X-Road software version number for Ubuntu and Red Hat packages is the same. However, the package naming conventions for Ubuntu and Red Hat are different which is why the whole package name is not identical.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Redhat: 
![image](https://user-images.githubusercontent.com/8038324/74512859-c4b3bd80-4f3b-11ea-919d-fd9c0b7878bc.png)

Ubuntu 18
![image](https://user-images.githubusercontent.com/8038324/74512882-d2694300-4f3b-11ea-8a09-2bc400eb6112.png)

For the Redhat Package is it correct that has the number of packges less than Ubuntu?

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question?

When I run the sudo apt-get install xroad-securityserver why it shows like this?

![image](https://user-images.githubusercontent.com/8038324/74518547-a0a9a980-4f46-11ea-9e7f-1eeb253a6a65.png)

Best Regards,
Dara Penhchet
