### ISSUE TITLE
Asking how to build the Redhat RPM from source code?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#377]
Dear @petkivim ,

Could I ask you about how to build the Redhat RPM package from the source code?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The easiest way to build the RPM packages is to follow the build instructions:

https://github.com/nordic-institute/X-Road/blob/develop/src/BUILD.md#dependency-installation-and-building-instructions

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your information

Best Regards,
Dara Penhchet
