### ISSUE TITLE
Package 'wget' missing in docker image for packaging rpm

### ISSUE THREAD

**Issue by mbert** [nordic-institute/X-Road#378]
Build of rpms will fail when trying to download jetty.

**Comment by mbert** [comment]
See pull request #379.

**Comment by petkivim** [comment]
Could you describe in more detail the steps that are required to reproduce the issue?

I am not able to reproduce the issue following the [build instructions](https://github.com/nordic-institute/X-Road/blob/develop/src/BUILD.md#dependency-installation-and-building-instructions) on a fresh Ubuntu 18.04 host. The build runs successfully and creates all the X-Road rpm packages, including ` xroad-jetty9`

```
$ ls -l packages/build/xroad-jetty9/redhat/RPMS/x86_64/

-rw-r--r-- 1 ubuntu docker 10160884 Feb 20 05:01 packages/build/xroad-jetty9/redhat/RPMS/x86_64/xroad-jetty9-6.24.0-0.20200219102213git476c260.el7.x86_64.rpm
```

Best regards,
Petteri

**Comment by mbert** [comment]
Thank you, @petkivim, you are right. It looks like I ran into a problem yesterday because I was doing something else wrong, so that the missing 'wget' popped up as a result of that. I will close both this issue and the PR.
