### ISSUE TITLE
Asking the TLS certificate with Information System is not working?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#386]
Dear @petkivim ,

Client (SUBSYSTEM:....) specifies HTTPS but did not supply TLS certificate?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Please read this Knowledge Base article:

https://confluence.niis.org/display/XRDKB/Client+Specifies+HTTPS+But+Did+Not+Supply+TLS+Certificate

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank you!

Best regards,
Dara Penhchet
