### ISSUE TITLE
Upgrade Xroad from 6.16 to 6.6.x

### ISSUE THREAD

**Issue by hainguyen291** [nordic-institute/X-Road#41]
Hi everyone,

How can I upgrade my Central Server and Security Server from v 6.16 to 6.6. I am going to HA CS, but the minimum requirements of version is 6.6.

Best regards,
Hai

**Comment by petkivim** [comment]
Hi @hainguyen291 

Version 6.16.0 is greater than 6.6.0 (6.16.0 > 6.6.0) so HA support is included in the version 6.16.0. Therefore, version upgrade is not required.

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi @petkivim ,

Aww I see, it is my bad. Thank you.

Hai.
