### ISSUE TITLE
Asking help how to install the XRoad Management Security Server in HA mode?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#426]
Dear @petkivim ,

Could I ask you how to install the Management Security Server in HA mode and how to use the PostgreSQL Cluster remotely or use the same as guideline to install the PostgreSQL with two instances (messagelog, serverconf) and replication one way only from master to slave with serverconf database?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The instructions for the Central Server HA setup are available here:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks. How about the Management Security Server should I need to install the HA with remote database cluster or only with local database for messagelog and serverconf database?

Best regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Security Server uses a different high-availability model than Central Server and therefore, the Central Server HA model is not applicable for Security Server. More information about HA alternatives for Security Server can be found here:

https://www.niis.org/blog/2018/6/25/balancing-the-load

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank you so much

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Hi  @darapenhchet,

When you have a Security Server cluster and all the nodes in the cluster share the same identity (`serverCode`), using the same database for all the nodes is technically possible. However, this kind of setup is not officially supported. Therefore, each Security Server must have its own database, local or remote.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank you so much.

Best Regards
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question? Why the Central Server EE-Production, and Management Security Server EE-Production have 3 IP Addresses? Could you explain me about it?

![image](https://user-images.githubusercontent.com/8038324/77256370-67303080-6ca0-11ea-839c-a5f8ebf7947d.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

It's because the environment has 3 Central Server nodes and each of them has its own management Security Server. 

Regards, 
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Why they don't use the HA Mode or Load Balancing? And why we need to install three Central servers and three management security servers?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

They are using the Central Server built-in HA mode. They have three active Central Server nodes that share the same configuration data either by using a shared database (cluster) or database multi-master replication. Each Central Server node has its own management Security Server to enable receiving and processing of management requests. In this way the environment remains  fully operational even if two nodes are unavailable.

Using an external load balancer with a Central Server cluster is not officially supported.

X-Road operator running an X-Road environment is free to decide how many Central Server nodes  are installed. Every X-Road environment requires at least one Central Server node and one management Security Server - additional nodes are optional and depend on the availability requirements if the environment. In addition to the number of Central Server nodes, also the configuration (e.g. global conf expiration period) affects the availability of the environment. 

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

So it means that their Management Security Server is not the HA or External Balancing right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The management services are using the built-in HA support of the Security Server - they are available on all the three management Security Servers. However, a single Central Server node has only one management Security Server. Without knowing the implementation details, it is impossible to say whether an external load balancer is used.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

So could I install the 3 Central Servers in HA Mode connects to 3 Management Security Servers or only one Management Security Server in External Load Balancing?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

> 3 Central Servers in HA Mode connects to 3 Management Security Servers

This is the recommended approach.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

It means we don't need to install the Management Security Server in External Load Balancing? So 3 Management Security Servers are only one member right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

> It means we don't need to install the Management Security Server in External Load Balancing?

There's no need to use an external load balancer.

> So 3 Management Security Servers are used with only one member right? so one central server will use one management security server right?

Yes.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

If I want to use the 3 Management Security Servers as External Load Balancing is it okay?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

When you have one management Security Server per Central Server node, there's no sense to use an external load balancer. If you want to setup a management Security Server cluster for each Central Server node, then an external load balancer can be used. In practice, it means that you should have at least two management Security Servers per Central Server node. Please study the documentation for details.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim,

Thank you so much for your information.

Best Regards,
Dara Penhchet

**Comment by JyrgenSuvalov** [comment]
Hey @darapenhchet 

If you want to have a 3 node setup, then that's correct. That's how we have done it in Estonia :)

Best regards,
Jürgen

**Comment by darapenhchet** [comment]
Dear @JyrgenSuvalov ,

Thanks @JyrgenSuvalov .

How about the 3 Management Security Server Member it has the same Member Code and SubSystemCode right?

Best Regards,
Dara Penhchet

**Comment by JyrgenSuvalov** [comment]
@darapenhchet Yep. We have 3 Management Security Servers just for management requests and they all have the same subsystem registered in it.

Best regards,
Jürgen

**Comment by darapenhchet** [comment]
@JyrgenSuvalov ,

Thank you. 
For the management requests we don't use the Central Server right?

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

A Central Server or Security needs two IP Addresses (one Private, and one Public) right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

Yes, that's correct.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I use only one private IP, and Public IP NAT to that private IP?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Yes, using public IP NAT is OK.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question about the 
CS1.example.com -> SS1.example.com, 
CS2.example.com ->SS2.example.com, 
CS3.example.com->SS3.example.com, 

we need to use the different DNS name and diferrent Member Code, Member Name, And SubSystem Code right? Is it correct or not?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Yes, each Central Server node and each management Security Server must have a unique DNS name. The management services must be published using the same member code and subsystem code on all the management Security Servers.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank you so much for your advise.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

May I ask you about the Load Balancing IP or Domain where should we update in our Security Server? If our server code and domain is different in Security server is it okay?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Security Server IP address or DNS that's registered on the Central Server is defined when the authentication certificate registration request is sent.

https://confluence.niis.org/pages/viewpage.action?pageId=6783483#HowtoConfigureCentralServer?-3.6Registeringtheauthenticationcertificate

>  If our server code and domain is different in Security server is it okay?

That's OK.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank so much for your answer.

Best Regards,
Dara Penhchet
