### ISSUE TITLE
Asking help about the IP in Security Server?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#446]
Dear @petkivim ,

Could I ask you about the NAT public IP to private IP in Security server do we need to change the Server Addresss to Public IP or not?

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

It depends on your environment. If the Security Server needs to communicate with resources (Central Server, other Security Servers, OCSP,  TSA) that are not located in the same network, a public IP is required. In case all the resources the Security Server communicates with are in the same private network and the Security Server does not need to be able to connect to the Internet in any situation, private IP is OK.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

If my Security Server is used to connect with both VPN Private LAN Security Server, Public Security Server what should I do?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi  @darapenhchet 

In that case the Security Server must have a public IP address, and the Security Server must be registered to the Central Server using either the public IP or a public FQDN. In addition, to make the connections inside the private LAN work, you need to configure a private DNS zone and/or network routes so that outgoing traffic to the public IP/FQDN of the Security Server is routed to the private IP instead.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your advice.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,
Could I ask you one more question?

Configuration source cannot be reached, check source URL in uploaded anchor file
![image](https://user-images.githubusercontent.com/8038324/78257107-a02f9700-7523-11ea-91f0-763ee02f1266.png)

Why it shows error like this when I am importing the anchor configuration file?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Your Security Server is not able to connect to the Central Server port 80 - global configuration is downloaded from there.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks so much. 
Could I ask you one more question? When this error log always show I have not done anything and it shows the error like this?

![image](https://user-images.githubusercontent.com/8038324/78258598-ab83c200-7525-11ea-8676-1ebb97681fef.png)


Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

It's because you have not configured the server yet. It'll disappear once the server is configured. 

Regards, 
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your answer.

Could I ask you more question related to the TimeStamp Authority Server? How could I check it is working well or not? Why do we need the Timestamp Authority server? and how to monitor it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The Security Server diagnostics view shows if the network connection between the Security Server and timestamping service is OK. However, it does not check that the timestamping service is returning valid timestamps, it only checks that the Security Server is able to establish a network connection to it. In case you need additional monitoring, you need to implement your own monitoring tools or alternatively ask your timestamping service provider if they have some monitoring tools available.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank you so much. 

I want to ask you one more question. If I have lost the Database for Central Server what should I do? Because I have used the Patroni and after I have restarted it lost all databases

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Hopefully you have a Central Server application backup file or a backup file of the Central Server host. You can then restore the backup and continue from there.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

The backup file will include the database data too right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Yes, the database is included in the backups. More information about the backups can be found at:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#13-configuration-backup-and-restore

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

For the speed between the Security Server  to Security from Information System if the Speed for each request is 600ms is it okay?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Performance of a Security Server depends on several things: hardware resources of the host (CPU count, RAM, disk space), how much memory has been allocated to proxy process, network speed, size of the message, sign and auth key length, number of concurrent clients etc. Therefore, without knowing all the variables it is impossible to say whether a throughput time of a message is good or bad.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you more question for External Load Balancing SS we configure only the SSL Passthrough only on port 5500, and 5577 right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

Yes, only ports 5500 and 5577 of the Security Servers should be load balanced, and SSL termination must be done by the Security Server. Therefore, the LB must be configured to use SSL passthrough.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

But if I don't passthrough the port 80 or 443, I cannot access it with information system with RESTful .

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

There are three different use-cases that include an external load balancer:

- A load balancer (LB 1) between service consumer(s) and a Security Server cluster.
- A load balancer (LB 2) between service providers and a Security Server cluster or a single Security Server.
- An external internet-facing load balancer (LB 3) that distributes inbound requests from other Security Servers to a Security Server cluster.

![external_load_balancing_1](https://user-images.githubusercontent.com/575897/78668125-c8801280-78e2-11ea-907e-60d03269e29a.png)

The first two scenarios are about distributing load between the Security Server and an information system and they have always been supported by the Security Server. 

The ports 5500 and 5577 of the Security Servers are load balanced in case of LB3. In case of LB1 (which seems to be the setup that you're configuring), ports 80 and 443 are load balanced.

More information is available here:

https://www.niis.org/blog/2018/6/25/balancing-the-load

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank you so much. If I include the LB1 or LB2 with the LB3 nginx is it okay to passthrough all that connection to Security Servers?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Yes, that's possible.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question? Why my security server always error like this?

`2020-04-13 11:44:23,545 [qtp442205321-72] ERROR e.r.x.proxy.conf.CachingKeyConfImpl - Failed to get authentication key
com.google.common.util.concurrent.UncheckedExecutionException: Signer.KeyNotFound: Could not find active authentication key for security server`

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Have you activated the authentication key of your Security Server?

![Screenshot 2020-04-13 at 9 52 20](https://user-images.githubusercontent.com/575897/79099350-96e8ca80-7d6c-11ea-83ac-d63f31650ae4.png)

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I have activated it already, but it still error like that. Could it is caused by OCSP Responder?

Best Regards
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

In addition, the authentication certificate must have a valid OCSP response. What does the diagnostics page say about the OCSP responder - is the connection OK? You could also try to empty the OCSP cache and see if it helps:

https://confluence.niis.org/pages/viewpage.action?pageId=17859927

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

How to make the OCSP Responder more stable with our Security Server?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

OCSP responder is an external dependency and its configuration depends on the software that you're using. Please consult the software vendor and/or user community of the software on questions regarding its configuration.

From X-Road's point of view OCSP responder can be made more fault tolerant by disabling `verifyNextUpdate`, making the `ocspFetchInterval` shorter  and adjusting the `ocspFreshnessSeconds` value. More information about the alternatives can be found at:

- https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#161-verify-next-update
- https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#162-ocsp-fetch-interval
- https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-syspar_x-road_v6_system_parameters.md#4-central-server-system-parameters

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks, I will check that configuration. 

`From X-Road's point of view OCSP responder can be made more fault tolerant by disabling verifyNextUpdate
`
it means we can disable the OCSP verification right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

> it means we can disable the OCSP verification right?

No, OCSP verification cannot be disabled. Only verification of the OCSP response's `nextUpdateField` can be disabled, but it does not mean disabling the whole OCSP verification.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I will try to test with it. Thanks so much for your help.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one question?
For Monitoring Security Server, what will we install it?

![image](https://user-images.githubusercontent.com/8038324/79434074-11794a80-7ff8-11ea-9f30-7cf0c71c300c.png)


Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Yes, you need a Security Server for sending monitoring queries. It can be a Security Server (Monitoring Security Server) or it can be the management Security Server (Management Security Server) too.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank so much for your advice.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

If I installed the Management Security Server two servers, so do I need to install it on both servers or only one?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

You can add the monitoring client to only one of the management Security Servers or both of them - which ever works the best for you. Please remember that the management services must be published on all the management Security Servers regardless of what you decide to do with the monitoring client.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could you explain me more about the Management Security Server when we need to use it?

If I install it on both Management Security Server the data will be duplicate or not?

`Please remember that the management services must be published on all the management Security Servers`

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The management Security Server is required to publish management services that are used to register authentication certificates, register new clients, unregister clients, etc.

> If I install it on both Management Security Server the data will be duplicate or not?

Publishing management services on multiple Security Servers does not duplicate the data.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Which ports should I allow for all security server members if I have install the External Monitoring Security Server?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The monitoring queries are standard X-Road messages so the External Monitoring Security Server  must be able to access the ports `5500` and `5577` of members' Security Servers.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim 

How about the port 2080?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

No, only ports `5500` and `5577`. Port `2080` must not be accessible to external parties.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks you so much.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Do I need to upload the Monitoring Security Server to the Central Server like this right?
![image](https://user-images.githubusercontent.com/8038324/79733184-e6a43480-831e-11ea-8746-9990ea4e63ec.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

You need to upload `monitoring-params.xml` file that defines the monitoring client that is used to access the monitoring data. However, it does not define any specific Security Server that's used for monitoring - the monitoring client can be registered on any Security Server.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim 
For the Monitoring Security Server should we use the Https or Http?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

It's up to your organization's security requirements. In general, the use of https is recommended.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thank for your advice. Could I ask you one more question about the External Load Balancer with Security Server how could I check the health of both Security Servers from SSL Path-through? And how could I pass the Remote Client IP to upstream Security Server?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

> how could I check the health of both Security Servers from SSL Path-through? 

You can use the health check interface provided by the Security Server. More information can be found at:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md#34-health-check-service-configuration

> And how could I pass the Remote Client IP to upstream Security Server?

Unfortunately, the Security Server does not provide built-in support for this. The client would have to include its own IP address to the request (e.g. using a custom HTTP header) or there could be an additional proxy between the client information system and client Security Server that would add the client IP to the request using `X-Forwarded-For` HTTP header. Either way, the implementation takes place on the client-side.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your advice. 

`
The third alternative is that you implement this feature and add it to the Security Server.
`
I am clear how to do it yet. If I can do it I will add this feature.

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The easiest alternative is to contact one of the X-Road Technology Partners and order the work from them:

https://x-road.global/xroad-technology-partners-companies

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I am not sure about it yet. And Thanks for your suggestion.

Best Regards, 
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Based on the requsted with 1000 users with 10000 requests the response it likes this. Why it is error like this?

![image](https://user-images.githubusercontent.com/8038324/80079649-c4a6ee00-857a-11ea-827d-9856b241e98a.png)

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Could you please describe your test setup in more detail? How often the error occurs, e.g. how many errors per 1000 messages?

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I think maybe because of my Network Problem.

Best Regards,
Dara Penhchet
