### ISSUE TITLE
Asking help about the XRoad Package with custom own release?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#490]
Dear @petkivim ,

Could I ask you if I want to release the new packages of XRoad how could I update it with the current installation one? Because the Current Installation is Snapshot one and I want to build the release.

![image](https://user-images.githubusercontent.com/8038324/81159690-70a4fc00-8fb3-11ea-80ea-1f15a70516b9.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

There is a version update tool available in the X-Road core repository:

https://github.com/nordic-institute/X-Road/blob/develop/src/version_change.sh

The purpose of the tool is to update the version in develop branch for the next development iteration, but it can also be used to set the current version as a release before rolling out to production.

The tool automatically upgrades/downgrades the version number in all required files:

*  `src/gradle.properties`
* `CHANGELOG.md`
* `src/packages/xroad/debian/changelog`
* `src/packages/xroad-jetty9/debian/changelog`
* `src/packages/build-rpm.sh`

The tool also allows for updating the current version to a release version by changing `x.y.z-0` to `x.y.z-1` in the deb changelogs and by adding the current date into `CHANGELOG.md`.

Usage:

`./version_change [--release] <version>`

The version parameter must be in the format `x.y.z`. The `--release` option is used to change the deb changelog version from `x.y.z-0` to `x.y.z-1`. The `--release` option can also be used without providing the version parameter. You can also downgrade to a lower version (only works if the wanted version can be found in `CHANGELOG.md` - also wipes clear the newer changes in the log)

**N.B.** You still need to fill in the correct changes into `CHANGELOG.md` normally. The tool only updates the version number and date. The tool looks up the current version from `CHANGELOG.md` (from the row with the first match of ##) and updates the new release date by replacing the string `UNRELEASED`.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks your information. May I know how to put the *.deb and *.rpm in the remote artifactory. Could you share me how to do it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

We use Artifactory's REST API to deploy the packages. Unfortunately, our release scripts are not publicly available. Please consult Artifactory's documentation for details:

- https://www.jfrog.com/confluence/display/JFROG/RPM+Repositories
- https://www.jfrog.com/confluence/display/JFROG/Debian+Repositories
- https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks do you use the opensource version right?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Unfortunately, the open source version does not support rpm and deb repositories. Therefore, we're using Artifactory Pro which requires a commercial license. However, you can manually create and host rpm and deb repositories on any HTTP server. [reprepro](https://wiki.debian.org/DebianRepository/SetupWithReprepro) and [createrepo](http://yum.baseurl.org/wiki/RepoCreate.html) will help you to do that.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks you so much

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question how about the Architecture we should use all or amd64, i386?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet,

The hardware requirements are documented here:

- https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md#23-requirements-for-the-security-server
- https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide_for_rhel7.md#23-requirements-for-the-security-server

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks you.

Best Regards, 
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

For Architecture should we build both amd64 and i386 separately or just build the Architecture with all?

When I have built with al,l it has an error like this.

![image](https://user-images.githubusercontent.com/8038324/81362891-22efd700-910c-11ea-93bd-299482275ae4.png)


Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Since X-Road requires 64-bit platform, you should build `amd64` only.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim,

Oh, I see. Thank you so much.

Best Regards,
Dara Penhchet
