### ISSUE TITLE
Asking help about the has not suitable certificates

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#513]
Dear @petkivim ,

Do you know about this error?
Caused by: ee.ria.xroad.common.CodedException: Signer.InternalError: Member 'SUBSYSTEM:DEV/GOV/DEV-0003/_API' has no suitable certificates

And one more is

ee.ria.xroad.common.CodedException: IncorrectValidationInfo: OCSP response is too old (thisUpdate: Fri May 22 10:43:52 ICT 2020)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

As the error message says, the OCSP response is too old which is why it is considered invalid. Possible reasons for that are discussed [here](https://github.com/nordic-institute/X-Road/issues/197#issuecomment-531641042).

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I have disabled it already, but it still not working. Could you help where could I fix it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The problem is not about `nextUpdate` - which can be disabled. Based on the error message, the problem is that the difference between the current time (=the moment when OCSP response's validity is verified) and `thisUpdate` is bigger than `ocspFreshnessSeconds`. One alternative to fix the problem is to increase the `ocspFreshnessSeconds` value. Another alternative is to lower the `ocspFetchInterval` value which means that OCSP responses are fetched more ofter. However, that may not resolve the problem if your CA does not issue new OCSP responses often enough. In that the best way to go is to increase the `ocspFreshnessSeconds` value.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I have set the CA with OCSP to update the CRL with a refresh interval of 10 minutes? so what should I change in Security Server?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The configuration below should work for you:

`verifyNextUpdate` = `false`
`ocspFreshnessSeconds` = 3600
`ocspFetchInterval` = 600

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim,

For the 
`ocspFreshnessSeconds = 3600
ocspFetchInterval = 600`

Where could I modify it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The instructions for changing `ocspFreshnessSeconds` can be found [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-syspar_x-road_v6_system_parameters.md#42-system-parameters-in-the-database), and the instructions for changing `ocspFetchInterval` can be found [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#162-ocsp-fetch-interval).

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I change only on the Central Server?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The both configuration items are defined on the Central Server. There's no need to modify the Security Server configuration.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks. Could I ask you one more question? 

Message exchange between security server and operational data monitoring daemon we use the port 2080. If I use the Security Server Monitoring Server should I allow that port for the Security server Monitoring Server?

**Comment by petkivim** [comment]
Hi @darapenhchet 

No, port `2080` must not be opened to external parties as it was discussed [here](https://github.com/nordic-institute/X-Road/issues/446#issuecomment-616087320).

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I have installed it already and it shows the Warning: no privileges were granted for pubic

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

`no privileges were granted for public` seems to be a PostgreSql error message. In what situation the error is shown? And what X-Road version you are using? We have implemented some quite significant changes to the Security Server database layer lately.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

What should I do if i use version 6.23.0?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The recent changes are not included in version 6.23.0, and the problem is caused by something else. I have not come across the error message before.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks so much.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

The Warning came up during the installation of the monitoring modules, which log is responsible and where could I find it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

It seems to be a warning that comes out every time when operational monitoring is installed. No further actions are needed, you can just ignore the warning.

> WARNING:  no privileges were granted for "public"

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim,

Thanks for your support.

Best Regards,
Dara Penhchet
