### ISSUE TITLE
Modify and compile Xroad

### ISSUE THREAD

**Issue by hainguyen291** [nordic-institute/X-Road#52]
Hi everyone,

I am trying to modify country name to VN and recompile Xroad as the following instruction: https://github.com/egobsv/Tenoli-LAT#modificaci%C3%B3n-del-pa%C3%ADs. So, I going to create new [4 classes](https://github.com/egobsv/Tenoli-LAT/tree/master/compilar)  including 3 classes:
- VNBCYAuthCertificateProfileInfo
- VNBCYCertificateProfileInfoProvider
- VNBCYSignCertificateProfileInfo
by cloned three classes:
- FiVRKAuthCertificateProfileInfo
- FiVRKCertificateProfileInfoProvider
- FiVRKSignCertificateProfileInfo

Also, clone FISubjectClientIdDecoder.java class to VNSubjectClientIdDecoder.java by modiying 'FI' to 'VN'. However, when run `./build_packages.sh` to recompile, I got following errors:

![image](https://user-images.githubusercontent.com/12641471/47629441-a589f480-db6d-11e8-994c-239f52694010.png)

![image](https://user-images.githubusercontent.com/12641471/47629465-c4888680-db6d-11e8-97ba-6f46c3b51ec0.png)

I don't know how to start. There are no document mention about how to create these 4 classes appropriated with your country PKI. Should I use Ejbca classes to implement this instead? If yes, how can I do it?

Best regards,
Hai

**Comment by petkivim** [comment]
Hi @hainguyen291 

You're receiving the errors, because your code  changes do not meet the `checkstyle` requirements for X-Road. `checkstyle` configuration files defining the rules can be found at:

https://github.com/nordic-institute/X-Road/tree/develop/src/config/checkstyle

X-Road Knowledge Base has an article about certificates:

https://confluence.niis.org/pages/viewpage.action?pageId=4293076

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi @petkivim ,

But how can I got errors from checkstyle? I clone FiVRK classes, and just change FI to VN only. I double checked these classes already, all of them are almost the same as origin classes except VN value. It is weird. I also tried to use original FiVRK classes with VN value instead, but it didn't work too. It seems that, only FI value is acceptable for these classes. Thats why I wonder if I need to implement Ejbca classes rather than FiVRK.

Regards,
Hai

**Comment by hainguyen291** [comment]
Hi @petkivim 

I am going to implement my own Ejbca CA, so I think I should use Ejbca classes instead, don't I?

Regards,
Hai

**Comment by hainguyen291** [comment]
Btw: I am using notepad++ to edit classes.

I have one more question. Why EjbcaSignCertificateProfileInfo doesn't have SerialNumber info as FiVRKSignCertificateProfileInfo? Can I add more field to this file?

Regards,
Hai

**Comment by hainguyen291** [comment]
Hi @petkivim ,

I didn't change anything and rebuild, however I still got error as below image

![image](https://user-images.githubusercontent.com/12641471/47725353-fba08a00-dc8a-11e8-92ac-19c500f8f562.png)

I integrated my EJBCA on Xroad, using original EjbcaSignCertificateProfileInfo.java class. 

![image](https://user-images.githubusercontent.com/12641471/47760881-ece8c000-dce8-11e8-8187-a4c3f1623320.png)

![image](https://user-images.githubusercontent.com/12641471/47760979-5072ed80-dce9-11e8-8cec-0a3e6b7b7f61.png)

So, It only give three fileds of profile including: Instance identifier, Member class and Member code.  Number 1 in the above image is testCA, and number 2 is mine. I can tested sending request succefully with testCA as usual, but my own Ejbca. The status of certificates with my Ejbca are at good state already. I check logs, it show that 

>com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: SslAuthenticationFailed.InvalidCertPath.IncorrectValidationInfo: OCSP responder is not authorized for given CA Please see the server log to find more detail regarding exact cause of the failure.
java.lang.NullPointerException

I don't know if I need to customise Ejbca profile adding serialNumber field. 

Regards,
Hai

**Comment by petkivim** [comment]
Hi @hainguyen291 

Are you running Central Server or Security Server on the same host that you use for building the software?

Have you configured an OCSP service for your EJBCA instance and uploaded its certificate to Central Server as described here:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#111-adding-an-approved-certification-service

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi @petkivim 

I build 2 virtual machines on my own computer. One for CS and the orther for SS. I did configure an OCSP service 

![image](https://user-images.githubusercontent.com/12641471/47798662-6b7e4580-dd5b-11e8-887e-ff0bc4a13390.png)

I did this step already. 

Regards,
Hai

**Comment by petkivim** [comment]
Hi @hainguyen291 

I can see that you have configured OCSP for the intermediate CA, but have you configured it for the root CA too? You must configure OCSP for the root CA as well, because it is used for fetching OCSP responses for the intermediate CA's certificate. Another alternative is to configure the current intermediate CA as a root CA.

`serialNumber` is not required - the reasons as explained here:

https://confluence.niis.org/pages/viewpage.action?pageId=4293076

> Every CA has a certificate profile that defines what information is stored in what fields in the certificate: what fields are required, what fields are optional, allowed values for some fields etc. The information required by the X-Road must be present in the certificates, but the fields where it’s stored may vary between different CAs. The X-Road requires the following information to be present in the certificates: instance identifier, member class and member code.

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi @petkivim ,

Thanks for your information. I solved this.

Best,
Hai
