### ISSUE TITLE
Asking help about the Client Must use POST request method instead of GET error?s

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#532]
Dear @petkivim ,

Could I ask you about this error?

![image](https://user-images.githubusercontent.com/8038324/83596215-4c2a4880-a58e-11ea-9550-377c3cdbf8ba.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The SOAP interface supports `POST` HTTP method only. The error message means that a request has been sent using the `GET` method instead of `POST`.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Why I always get this error? How could I prevent this error? and how could I check where is that request come from?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

You can check the source of the request from the client proxy access log: `/var/log/xroad/clientproxy_access.log`. To prevent the error, you could block access from sources that are sending requests causing the error. Or alternatively, you could write a script that removes unwanted entries from the operational monitoring database.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your info.

Best Regards, 
Dara Penhchet
