### ISSUE TITLE
Cannot login center server

### ISSUE THREAD

**Issue by nguyenhabkit** [nordic-institute/X-Road#64]
Hi everyone,
I built code Xroad version 6.16.0 and created my own repository, and then I installed centerserver successfully without any error, but I cannot login in CENTRAL SERVER ADMINISTRATION (with ubuntu user during the installation). I remove and reinstall but I still get this error:
![screenshot_4](https://user-images.githubusercontent.com/37961023/48888350-00f58c80-ee65-11e8-87ef-4a7ff0e682a6.png)
Please have a look, and let me know what I should do now? 
Thanks,
Ha.

**Comment by petkivim** [comment]
Hi @nguyenhabkit 

Have you read the section about user management in the Central Server [user guide](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#2-user-management)?

Have you checked that the user is a member of `xroad-system-administrator` group?

Regards,
Petteri

**Comment by petkivim** [comment]
Hi @nguyenhabkit 

> So I guess, maybe because of conflict between building 's environment and installing 's environment when I built code and installed xroad center on the same server.

This is probably the reason for the problem. You should not build and run X-Road on the same server. Instead, you should have a dedicated server for building the software.

Regards,
Petteri
