### ISSUE TITLE
Where is the *.deb after build code successfull 

### ISSUE THREAD

**Issue by thuannc** [nordic-institute/X-Road#68]
Hi
I have build source code successs 
after that post build script seem to work fine with "exit 0"
but i can not find out the *.deb in X-Road/src/packages folder, where can i find it out?
Thank you
thu@nnc

The build log look like:

...
BUILD SUCCESSFUL in 8m 22s
...
Checking for unpackaged file(s): /usr/lib/rpm/check-files /workspace/src/packages/build/xroad-jetty9/redhat/BUILDROOT/xroad-jetty9-6.20.0-0.20181130123550git0fb05ee.el7.x86_64
Wrote: /workspace/src/packages/build/xroad-jetty9/redhat/RPMS/x86_64/xroad-jetty9-6.20.0-0.20181130123550git0fb05ee.el7.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.MOjlnv
+ umask 022
+ cd /workspace/src/packages/build/xroad-jetty9/redhat/BUILD
+ rm -rf /workspace/src/packages/build/xroad-jetty9/redhat/BUILDROOT/xroad-jetty9-6.20.0-0.20181130123550git0fb05ee.el7.x86_64
+ exit 0

**Comment by kmpsaravanan** [comment]
Hi thuannc, while compiling the xroad code (cloned from NIIS github repo), getting error in passwordstore test. The build is failing at TASK common-util:test at ee.ria.xroad.common.util.PasswordStoreTest > runTest FAILED
   java.lang.RuntimeException at PasswordStoreTest.java:45
did u face this issue or any idea what action to be taken?
I am compiling the code in Ubuntu 14.04 VM

Regards,
Saro
