### ISSUE TITLE
Jetty download fails when building packages

### ISSUE THREAD

**Issue by mbert** [nordic-institute/X-Road#691]
In the script `./src/packages/download_jetty.sh` the `wget` command is used to download the jetty distribution. This no longer works, because the build docker image from `./src/packages/docker-compile/Dockerfile` which is based on `ubuntu:18.04` does not contain `wget` anymore. 

Hence a fix is needed: either install `wget` in the build image build or use `curl` instead in the jetty download script.

I guess that this problem has remained unnoticed because the build images have probably been built a long time ago, so that the package list change in `ubuntu:18.04` had no effect for your builds. 

Could you please check?

I was trying to build from tag `6.24.0`.

**Comment by petkivim** [comment]
How did you try to build the installation packages? You should use the `./src/build_packages.sh` script which takes care of compiling the code and building the packages. The build instructions are documented [here](https://github.com/nordic-institute/X-Road/blob/develop/src/BUILD.md).

The Docker file that you're referring to (`./src/packages/docker-compile/Dockerfile`) is meant for our CI tools only, and it's not meant to be used manually by developers.

**Comment by mbert** [comment]
I am using a shell script mimicking the build instructions from the Jenkinsfile. This seems to make sense, because we need to produce packages for all the various distributions. 

But if I'm right, you should get the same problem as I did once you simply delete the build docker image in your CI environment so that it needs to be rebuilt.

**Comment by petkivim** [comment]
We tested the scripts in a clean environment and unfortunately, we were not able to reproduce the issue. The Docker image that you're referring to is for compiling the code, and the script `./src/packages/download_jetty.sh` is not needed until packaging. And the image that is used for packaging (`./src/packages/docker/deb-bionic/Dockerfile`) already [installs](src/packages/docker/deb-bionic/Dockerfile) `wget`. Therefore, the current images should be OK.

In case you try to run `build_packages.sh` inside a container created from `./src/packages/docker-compile/Dockerfile `, the process probably fails because `wget` is missing. However, that's not the way how the image is meant to be used.

**Comment by mbert** [comment]
OK, thank you, I will need to go through the process again and compare the Jenkinsfile and my script step by step. It used to work with previous X-Road releases, now it no longer does. So something must have changed.

**Comment by petkivim** [comment]
You're welcome! The most simple solution is to install Docker on your Jenkins and run the `build_packages.sh` script. Since Docker is installed, Jenkins will build packages for all the supported distributions.

**Comment by mbert** [comment]
I have looked at the script now, and I seem to remember why I preferred to look into the Jenkinsfile rather than into that script: the compile step is done on the host on which some build dependencies need to be installed before. Should not docker be used throughout the whole process? I don't think that having to install native software (like ruby, gradle etc.) on my build slaves is what I want. 

I am currently trying out a modification to the build_packages that automates building the build images (like in Jenkinsfile) and performs the whole build inside docker if installed. Will need some changes to the build instructions if successful. I'll send you a PR if successful.
