### ISSUE TITLE
Move security server to new xroad system?

### ISSUE THREAD

**Issue by nguyenhabkit** [nordic-institute/X-Road#71]
Hi everyone,
I have a xroad system including: 
- 01 Center server  is named CS1
- 01 Security server is named SS1, and SS1 is a member of CS1
Now, I install a new center server is named  CS2, and I want to move SS1 to be a member of CS2 without re-installing SS1.
Have you has any idea to do this?

Thanks,
Ha

**Comment by petkivim** [comment]
Hi @nguyenhabkit 

Moving a Security Server from one instance to another is not supported. You must install a new Security Server and register it to CS2.

Regards,
Petteri

**Comment by nguyenhabkit** [comment]
Hi @petkivim,
I got it, thanks you so much!
Ha.
