### ISSUE TITLE
Install Central Server on Centos 8

### ISSUE THREAD

**Issue by kommalyskb** [nordic-institute/X-Road#727]
Hello, I want to install central server on centos 8, there are any document or central server install on Ubuntu only

**Comment by petkivim** [comment]
Hi,

The Central Server supports only Ubuntu 18.04 LTS and support for Ubuntu 20.04 LTS will be added in version 6.25.0. Unfortunately, the Central Server does not support RHEL and/or CentOs, and adding the support is not currently in our plans.

Best regards,
Petteri
