### ISSUE TITLE
Configuring external IP address to x-road server local interface for in-house service communication

### ISSUE THREAD

**Issue by zpotoloom** [nordic-institute/X-Road#755]
As a Security Server user with multisite clustered setup I would like to reduce the communication path between in-house service communication.

With the default setup X-road uses round-robin(?) to find the subsystem Security Server and this creates a rather long path.

Client1 and Service2 registered on Security Servers: 1.1.1.1, 2.2.2.2
![image](https://user-images.githubusercontent.com/2527738/96757011-88473400-13dd-11eb-8ce1-418a82f28a9a.png)

Considering a scenario where the X-road clusters External IP addresses will be configured as local aliases for each cluster members. With this configuration when in-house client subsystem contacts a service subsystem that is configured on the same cluster will happen inside the same node that received the client connection.

Client1 and Service2 registered on Security Servers: 1.1.1.1, 2.2.2.2
![image](https://user-images.githubusercontent.com/2527738/96756804-44542f00-13dd-11eb-9dda-ef276d26f6f1.png)

Or... should there be a different approach to finding a target Security Server
that detects locally configured subsystem before resorting to making a request to external IP address.

**Comment by petkivim** [comment]
> With the default setup X-road uses round-robin(?) to find the subsystem Security Server and this creates a rather long path.

The internal client-side load balancer is a built-in feature of the X-Road Security Server and it is operating on “Fastest Wins” basis. When a service is registered on multiple Security Servers (same organization, same subsystem, same service code) the server that responds the fastest to TCP connection establishment request is used by a client Security Server. Once a provider Security Server is selected, it will be used for subsequent requests by the client until the TLS session cache expires or a connection attempt fails. [More information on load balancing](https://www.niis.org/blog/2018/6/25/balancing-the-load).

The internal load balancer can be bypassed by defining the server code of the target Security Server in the request. In this way, the request is sent directly to the Security Server identified by the server code. In your case, both clusters should have their own unique server code and by defining the server code in the request, you can target the request to the same cluster. However, also in this case the request is sent to the target Security Server using the address that has been registered in the global configuration which in your case is the address of the public LB. 

In the X-Road Message Protocol for SOAP, the server code is defined in the SOAP headers:

```
   <SOAP-ENV:Header>
      <xroad:client id:objectType="MEMBER">
         <id:xRoadInstance>EE</id:xRoadInstance>
         <id:memberClass>GOV</id:memberClass>
         <id:memberCode>TS1OWNER</id:memberCode>
      </xroad:client>
      <xroad:service id:objectType="SERVICE">
         <id:xRoadInstance>EE</id:xRoadInstance>
         <id:memberClass>GOV</id:memberClass>
         <id:memberCode>TS1OWNER</id:memberCode>
         <id:serviceCode>clientReg</id:serviceCode>
      </xroad:service>
      <xroad:server id:objectType="SERVER">
         <id:xRoadInstance>EE</id:xRoadInstance>
         <id:memberClass>GOV</id:memberClass>
         <id:memberCode>TS1OWNER</id:memberCode>
         <id:serverCode>TS1</id:serverCode>
      </xroad:server>
      <xroad:id>8770348d-c5f1-4f23-989e-7dd91fb59eff</xroad:id>
      <xroad:protocolVersion>4.0</xroad:protocolVersion>
   </SOAP-ENV:Header>
``` 

In the X-Road Message Protocol for REST, the server code is defined in the `X-Road-Security-Server` HTTP header:

```
X-Road-Security-Server: INSTANCE/MEMBERCLASS/MEMBERCODE/SERVERCODE
```

**Comment by zpotoloom** [comment]
With new light regarding the workings of the internal client-side load balancer it seems to me that it would be enough to configure just the local cluster external IP as an alias to individual nodes for the purpose of skipping the extra step of going through the external load balancer.

![image](https://user-images.githubusercontent.com/2527738/96979069-a9b43700-1527-11eb-9cd2-2131567e4e62.png)

**Comment by petkivim** [comment]
We haven't tested that kind of configuration in practice so I cannot guarantee that it'll work. However, you can try it out.

**Comment by zpotoloom** [comment]
Closing for now, will try and document results in the future.
