### ISSUE TITLE
Change port for distribution of the global configuration from 80 to 443 on Central Server.

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#774]
Dear @petkivim!

I want change port for distribution of the global configuration from 80 to 443 on Central Server. URL download global configuration win change from http://cs.server/internalconf to https://cs.server/internalconf. 
Can you give me solution?

Thank you very much!

**Comment by petkivim** [comment]
Hi @trungnv0412 

Changing the global configuration port from `80` to `443`, and from `http` to `https` is not currently officially supported. Therefore, unfortunately, there's no documentation available on the topic. However, the change requires updating Nginx configuration file that's located at `/etc/xroad/nginx/xroad-public.conf`. You could compare the configuration to the management services that already use `https`. Their  configuration is locared at `/etc/xroad/nginx/xroad-center.conf`. In case you change the configuration, please note that the configuration files are overwritten on version updates.

Regards,
Petteri
