### ISSUE TITLE
Feature request: health check service and HSM failure detection

### ISSUE THREAD

**Issue by zpotoloom** [nordic-institute/X-Road#804]
https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md#34-health-check-service-configuration

Health check service currently does not monitor signing certificate:
In addition to implicitly verifying that the xroad-proxy service is running, the health checks verify that:

- The server **authentication key** is accessible and that the OCSP response for the certificate is good. This requires a running xroad-signer service in good condition.
- The serverconf database is accessible.

https://github.com/nordic-institute/X-Road/blob/develop/src/proxy/src/main/java/ee/ria/xroad/common/util/healthcheck/HealthChecks.java#L57

> As it's not possible to generate the authentication key inside the HSM slot instead of Software token
> https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#32-configuring-the-authentication-key-and-certificate-for-the-security-server

**There is Option 2:**

- Add additional configurable feature to health check service to enable checking of the active signing tokens

> This check would need to check all the keys and certificates for registered and active clients

**Comment by petkivim** [comment]
Hi @zpotoloom 

Thanks for the enhancement request. Could you please submit it to the X-Road Service Desk that's the official channel for submitting enhancement and feature requests? Instructions can be found here:

https://github.com/nordic-institute/X-Road-development/#enhancement-requests-and-error-reports

1. [Sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account
2. Submit the request to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1)

Thanks,
Petteri
