### ISSUE TITLE
build packages

### ISSUE THREAD

**Issue by patrunomeister** [nordic-institute/X-Road#805]
I got this error about gradle version

![image](https://user-images.githubusercontent.com/482417/101884797-86a61b00-3b99-11eb-81b7-858b875aaa8c.png)

Any suggestions?
Thanks in advance

**Comment by petkivim** [comment]
Hi  @patrunomeister 

Have you followed the steps described [here](https://github.com/nordic-institute/X-Road/blob/develop/src/BUILD.md#dependency-installation-and-building-instructions)? You have to run three commands in this order:

```
$ ./prepare_buildhost.sh
$ ./update_ruby_dependencies.sh
$ ./build_packages.sh
```
Best regards,
Petteri

**Comment by patrunomeister** [comment]
Hi @petkivim 
Thank you for your answer
Yes, I have followed all three steps on the instructions. Only the last command fails because of gradle version...

**Comment by petkivim** [comment]
Hi @patrunomeister 

Unfortunately, I wasn't able to reproduce the problem on a fresh Ubuntu 18.04 LTS host - the build worked correctly. The Gradle version that's currently used by X-Road is 6.6 and it's included in the X-Road repository - you shouldn't install Gradle separate on the host. Please check that you don't have another Gradle version installed on your build host.

**Comment by patrunomeister** [comment]
I've started again to install the package on a fresh (VM) ubuntu 18.04. Before launching prepare_buildhost shell script I've installed manually Docker, Java, Ansible, gcc. But after running update_running and build_packages  I've got the same error  as before

**Comment by petkivim** [comment]
The `prepare_buildhost.sh` script takes care of installing all required components and dependencies except Ansible. In other words, the only thing that you have to install manually is Ansible since the `prepare_buildhost.sh` script takes care of the rest.

**Comment by patrunomeister** [comment]
Dear Petteri,
I've tried with:

- ubuntu 18.04
- ubuntu 18.04 desktop
- ubuntu 20.10

starting each time from the virtual machine installation and installing ansible manually before launching prepare_buildhost.sh. The error message is always the same, even the first error I've got is about proxy-ui-api 
Here the screenshot
Any idea? 

![image](https://user-images.githubusercontent.com/482417/102101032-6c36a080-3e2a-11eb-83dd-0905fea7969d.png)

**Comment by petkivim** [comment]
Hi @patrunomeister 

The build is now working and the error message is caused by a failed NPM audit in the `proxy-ui-api` module. It means that the build host is OK and as soon as the vulnerable dependencies are updated, you're able to build the packages successfully. The dependencies will be fixed tomorrow. In the meanwhile, you can also update them locally based on the NPM audit error report.

**Comment by petkivim** [comment]
Hi @patrunomeister 

The problem is fixed now. Just pull the latest changes from `develop` and run `./build_packages.sh` again.

**Comment by patrunomeister** [comment]
Thank you @petkivim for the prompt answer
Regards
VP
