### ISSUE TITLE
Problem installing xroad with ansible

### ISSUE THREAD

**Issue by DarioBernardo** [nordic-institute/X-Road#825]
Hi, I am trying to install xroad using ansible. 
I have configured my `xroad_hosts` file to have 1 cs-server, 1 ss-server, 1 cp-server and 1 ca-server and configured the ssh key path and user.
I am then executing the ansible playbook as explained [here](https://github.com/nordic-institute/X-Road/tree/develop/ansible#3-install-x-road-using-ansible) with the following command:
`ansible-playbook -i hosts/my_xroad_hosts.txt xroad_init.yml`

however the installation is unsuccessful and i get the following error at central server installation step:
```
TASK [xroad-cs : install xroad central server] *************************************************************************************************************************************************************
fatal: [cs.xxxxxx.xx]: FAILED! => {"changed": false, "msg": "No package matching 'xroad-centralserver' is available"}
```

I am not sure what's going on. I am either missing something (but then the documentation should be clearer) or there is some issue with the package manager. Thank you.

UPDATE: before launching the ansible command, if I log in into the central server and give the following commands:
`curl https://artifactory.niis.org/api/gpg/key/public | sudo apt-key add -`
`sudo apt-add-repository -y "deb https://artifactory.niis.org/xroad-release-deb $(lsb_release -sc)-current main"`
`sudo apt-get update`
and only after I launch the ansible-playbook, then it works. I believe something needs to be updated in the ansible commands for the cs server.

**Comment by petkivim** [comment]
Hi @DarioBernardo 

What's the operating system of the server hosting the Central Server? Supported operating systems for the Central Server are Ubuntu 18.04 LTS and Ubuntu 20.04 LTS.

Regards,
Petteri

**Comment by DarioBernardo** [comment]
Yes you are right, i was using the wrong distribution. Sorry. This ticket can be closed.
