### ISSUE TITLE
Changing default postgres passwords in config files causes ansible playbook installation fail 

### ISSUE THREAD

**Issue by DarioBernardo** [nordic-institute/X-Road#831]
Hi, I am sure I am missing something obvious. I am trying to change the default postgres passwords. For security reason I think would be better to have some proper passwords. I am trying to achieve this by editing the following files in `var_files` folder: 
 - cs_database.yaml: changing `database_admin_password`
 - ss_database.yaml:  changing `database_admin_password`, `opmonitor_admin_password`, `serverconf_password`, `opmonitor_password` and `messagelog_password`.

Unfortunately when i launch my ansible playbook command, installation fails saying that it was unable to authenticate to the database with user `postgres`. I am sure I need to change something else to, but I couldn't find anything in the documentation. 

As a side note, does the 5432 postgres port needs to be open to the world for the central server? because in that case it is necessary to have a proper password set up.

**Comment by petkivim** [comment]
Hi @DarioBernardo 

The `database_admin_password` is the password of the `postgres` user. The `database_admin_password` variable must be defined when using a remote database server or the default configuration of the local `postgres` user has been changed. It's the password of the `postgres` user. More information can be found [here](https://github.com/nordic-institute/X-Road/tree/develop/ansible#remote-database), [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md#26-remote-database-installation) and [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#26-remote-database-installation).

Passwords of the `serverconf`, `messagelog` and `opmonitor` databases are auto generated during the installation process. Also, the password of the Central Server database is auto generated during installation starting from version 6.24.0.

> As a side note, does the 5432 postgres port needs to be open to the world for the central server?

No, it shouldn't be opened to the world. If the Central Server application and database server run on the same host, it's enough to enable access from localhost.

Regards,
Petteri

**Comment by DarioBernardo** [comment]
brilliant, thank you.
