### ISSUE TITLE
Document "Service Metadata Protocol for REST" is not referenced under Protocol heading in X-Road documentation

### ISSUE THREAD

**Issue by arattur** [nordic-institute/X-Road#842]
Hi, I was search for document "Service Metadata Protocol for REST", but couldn't find reference to it on [X-Road documentation page](https://github.com/nordic-institute/X-Road/blob/develop/doc/README.md) under heading [Protocols](https://github.com/nordic-institute/X-Road/blob/develop/doc/README.md#protocols). At the moment there is only link to [SOAP-based Service Metadata Protocol](https://github.com/nordic-institute/X-Road/blob/develop/doc/Protocols/pr-meta_x-road_service_metadata_protocol.md). 

I managed to find the right file "[Service Metadata Protocol for REST](https://github.com/nordic-institute/X-Road/blob/develop/doc/Protocols/pr-mrest_x-road_service_metadata_protocol_for_rest.md)" in repository under [X-Road/doc/Protocols](https://github.com/nordic-institute/X-Road/tree/develop/doc/Protocols).

It would be nice if PR-MREST document would be listed under protocol list:
![missing_reference_to_PR-MREST](https://user-images.githubusercontent.com/34676396/105365334-d18a6800-5c06-11eb-8ff4-687c27f6ac51.png)

**Comment by petkivim** [comment]
Hi @arattur 

Thank you for pointing that out. PR-MREST has been added to the protocol list (d7c9cf9a).

Regards,
Petteri
