### ISSUE TITLE
It's possible to config specific HSM slot index?

### ISSUE THREAD

**Issue by nguyenhabkit** [nordic-institute/X-Road#88]
Hi @petkivim ,
With HSM device, for now it take so much time to scan all slot of HSM. However one SS uses only one slot, so how can I configure to load only the slot (I use xroad version 6.16.0)?
For example:
- The HSM device has 100 slots
- The SS uses slot index 82
I've just want to scan and load only slot index 82, instead scanning all 100 slots.

Thank you,
Ha

**Comment by nguyenhabkit** [comment]
I follow this thread: 
https://github.com/vrk-kpa/xroad-joint-development/issues/177
But it cannot be done (I use xroad version 6.16.0).
Please help me!

**Comment by petkivim** [comment]
Hi @nguyenhabkit 

With some HSM drivers, it is not possible to configure specific slots for the Security Server to use. In that case the Security Server will scan all available slots until the right key is found. Configuring a specific slot is not currently supported by the Security Server. There's an enhancement request in the X-Road backlog about this issue:

https://jira.niis.org/browse/XRDDEV-140

Regards,
Petteri
