### ISSUE TITLE
13 tests completed, 1 failed

### ISSUE THREAD

**Issue by DerSIlent** [nordic-institute/X-Road#890]
I tried using the native build (with sudo) and upon the `$ ./build_packages.sh` got the error

<img width="948" alt="error file" src="https://user-images.githubusercontent.com/24533690/108761512-3e1ebc80-754f-11eb-9013-5237cd2fb45e.png">

Included in the HTML error.

`<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=edge"/>
<link href="css/base-style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="content">
<h1>Test Summary</h1>
<div id="summary">
<table>
<tr>
<td>
<div class="summaryGroup">
<table>
<tr>
<td>
<div class="infoBox" id="tests">
<div class="counter">13</div>
<p>tests</p>
</div>
</td>
<td>
<div class="infoBox" id="failures">
<div class="counter">1</div>
<p>failures</p>
</div>
</td>
<td>
<div class="infoBox" id="ignored">
<div class="counter">0</div>
<p>ignored</p>
</div>
</td>
<td>
<div class="infoBox" id="duration">
<div class="counter">0.672s</div>
<p>duration</p>
</div>
</td>
</tr>
</table>
</div>
</td>
<td>
<div class="infoBox failures" id="successRate">
<div class="percent">92%</div>
<p>successful</p>
</div>
</td>
</tr>
</table>
</div>
<div id="tabs">
<ul class="tabLinks">
<li>
<a href="#tab0">Failed tests</a>
</li>
<li>
<a href="#tab1">Packages</a>
</li>
<li>
<a href="#tab2">Classes</a>
</li>
</ul>
<div id="tab0" class="tab">
<h2>Failed tests</h2>
<ul class="linkList">
<li>
<a href="classes/ee.ria.xroad.commonui.OptionalPartsConfBehavior.html">OptionalPartsConfBehavior</a>.
<a href="classes/ee.ria.xroad.commonui.OptionalPartsConfBehavior.html#shouldAddErrorsIfCannotReadConfigurationPartFile">shouldAddErrorsIfCannotReadConfigurationPartFile</a>
</li>
</ul>
</div>
<div id="tab1" class="tab">
<h2>Packages</h2>
<table>
<thead>
<tr>
<th>Package</th>
<th>Tests</th>
<th>Failures</th>
<th>Ignored</th>
<th>Duration</th>
<th>Success rate</th>
</tr>
</thead>
<tbody>
<tr>
<td class="success">
<a href="packages/ee.ria.xroad.common.request.html">ee.ria.xroad.common.request</a>
</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.397s</td>
<td class="success">100%</td>
</tr>
<tr>
<td class="failures">
<a href="packages/ee.ria.xroad.commonui.html">ee.ria.xroad.commonui</a>
</td>
<td>12</td>
<td>1</td>
<td>0</td>
<td>0.275s</td>
<td class="failures">91%</td>
</tr>
</tbody>
</table>
</div>
<div id="tab2" class="tab">
<h2>Classes</h2>
<table>
<thead>
<tr>
<th>Class</th>
<th>Tests</th>
<th>Failures</th>
<th>Ignored</th>
<th>Duration</th>
<th>Success rate</th>
</tr>
</thead>
<tbody>
<tr>
<td class="success">
<a href="classes/ee.ria.xroad.common.request.ManagementRequestSenderTest.html">ee.ria.xroad.common.request.ManagementRequestSenderTest</a>
</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.397s</td>
<td class="success">100%</td>
</tr>
<tr>
<td class="success">
<a href="classes/ee.ria.xroad.commonui.CertificateProfileInfoValidatorTest.html">ee.ria.xroad.commonui.CertificateProfileInfoValidatorTest</a>
</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0.243s</td>
<td class="success">100%</td>
</tr>
<tr>
<td class="failures">
<a href="classes/ee.ria.xroad.commonui.OptionalPartsConfBehavior.html">ee.ria.xroad.commonui.OptionalPartsConfBehavior</a>
</td>
<td>9</td>
<td>1</td>
<td>0</td>
<td>0.032s</td>
<td class="failures">88%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="footer">
<p>
<div>
<label class="hidden" id="label-for-line-wrapping-toggle" for="line-wrapping-toggle">Wrap lines
<input id="line-wrapping-toggle" type="checkbox" autocomplete="off"/>
</label>
</div>Generated by
<a href="http://www.gradle.org">Gradle 6.6.1</a> at Feb 22, 2021 7:28:13 PM</p>
</div>
</div>
</body>
</html>`

Any suggestions?
Thanks!

**Comment by petkivim** [comment]
Hi @DerSIlent 

Have you followed the [build instructions](https://github.com/nordic-institute/X-Road/blob/develop/src/BUILD.md)? In general, using `sudo` shouldn't be required for building the packages.

Are you trying to build the `develop` branch? Do you have any local customisations there or are you using the latest version from the master repo (=this repo)?

Best regards,
Petteri

**Comment by DerSIlent** [comment]
Hello @petkivim 

Yes, I followed the instructions building it natively. I should add that I didn't install any of the dependencies myself. 

I haven't made any changes myself (pulled from master branch).

Kind regards,
Stephan

**Comment by petkivim** [comment]
Hi @DerSIlent 

I tried to build the `develop` branch on Ubuntu 16.04 LTS on AWS using the following AMI:

```
xenial	server	release	20201014	ebs-ssd	amd64	eu-central-1	ami-0d971d62e4d019dcc			hvm
```

Unfortunately, I wasn't able to reproduce the issue. Instead, I was able to complete the build successfully running the following commands without `sudo`:

```
$ ./prepare_buildhost.sh
$ ./update_ruby_dependencies.sh
$ ./build_packages.sh
``` 

This is how the permissions of the file included in the error message should look like:

```
-rw-rw-r-- 1 ubuntu docker      17 Feb 23 14:05 fileHashes.lock
```

Best regards,
Petteri

**Comment by DerSIlent** [comment]
Hello @petkivim 

I re-installed my Ubuntu 16.04 LTS on the VPS but received a different error. This time it was during the `./update_ruby_dependencies.sh` part. 


`Errno::EACCES: Permission denied - /opt/X-Road/src/common-ui/.mvn
An error occurred while installing psych (3.0.3), and Bundler
cannot continue.
Make sure that `gem install psych -v '3.0.3'` succeeds before bundling.
`

Did not use `sudo `this time.

The steps I did was:

- create new user with sudo rights and change to user
- installed git and pulled using https://github.com/nordic-institute/X-Road.git
- cd into src and executed ./prepare_buildhost.sh and 
./update_ruby_dependencies.sh 


Kind regards,
Stephan

**Comment by petkivim** [comment]
Hi @DerSIlent 

Based on the error message (`Errno::EACCES: Permission denied`) the issue seems to be related to permissions. Did you clone the repository (`git clone ...`) using the same user and without `sudo`? Have you tried to run the build in the user's home directory?

Best regards,
Petteri

**Comment by DerSIlent** [comment]
Hello @petkivim 

My apologies for the delayed response!

Previous attempts were the same user without `sudo`, although pulling the repo into the home directory repo did the trick. Before I was installing it in the opt directory. 

Thank you for your time!

Kind regards,
Stephan
