### ISSUE TITLE
Deploy X-road to public domain

### ISSUE THREAD

**Issue by DerSIlent** [nordic-institute/X-Road#914]
Hello,

I have deployed X-road using ansible on a VM on my desktop. Everything works fine locally but now I want to have it on a public domain. 

I tried using a `reverse proxy` [using this guide](https://www.linode.com/docs/guides/beginners-guide-to-lxd-reverse-proxy). But my use-case did not work.

[containers should be working normally](https://user-images.githubusercontent.com/24533690/111474630-8be0ac00-872c-11eb-9022-d28f5e633abb.png)

I asked on [StackOverflow ](https://stackoverflow.com/questions/66554274/reserve-proxy-to-an-lxc-container/66561004?noredirect=1#comment117680029_66561004) this question but only got enough information that SSL cannot be proxied. 

`proxy`:
```
server {

        server_name ca.example.com;

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass https://futura-ca.lxd:4000/;
        }

        real_ip_header proxy_protocol;
        set_real_ip_from 127.0.0.1;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ca.katunka.me/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ca.katunka.me/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
   if ($host = ca.example.com) {
       return 301 https://$host$request_uri;
   } # managed by Certbot


       listen 80 proxy_protocol;
       listen [::]:80 proxy_protocol;

       server_name ca.example.com;
   return 404; # managed by Certbot


}

```

Could you show me what I'm doing wrong with the reverse proxy or another (better?) way of deploying the X-road public?

Kind regards,
Stephan

**Comment by petkivim** [comment]
Hi @DerSIlent 

LXD containers are meant for local development and testing, not for a public deployment. For an X-Road deployment that's accessible from the Internet, it's recommended to use virtual machines or [Docker](https://hub.docker.com/u/niis) containers.

Best regards,
Petteri

**Comment by DerSIlent** [comment]
Dear @petkivim ,

Thank you! I missed that part of the documentation, my bad.

I'm now on a fresh VPS using ubuntu 20.04. After installing Docker and git I tried to build it but I got some errors.

When I tried to build it without `sudo`:
```
sruiz@vultr:~/X-Road/src$ ./build_packages.sh -d
Building in docker...
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%22gid%22%3A%221000%22%2C%22uid%22%3A%221000%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&q=1&rm=1&shmsize=0&t=xroad-build&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
*** Error building build image.

```

without `sudo`:
```
sruiz@vultr:~/X-Road/src$ sudo ./build_packages.sh -d
Building in docker...
Sending build context to Docker daemon  3.072kB
Step 1/13 : FROM ubuntu:18.04
 ---> 329ed837d508
Step 2/13 : ARG uid
 ---> Using cache
 ---> c90c26a78ad9
Step 3/13 : ARG gid
 ---> Using cache
 ---> 09a9f9d73c0a
Step 4/13 : ENV JRUBY_VERSION="9.1.17.0"
 ---> Using cache
 ---> ea26bd313849
Step 5/13 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> f7c9573fc7ad
Step 6/13 : RUN groupadd -g $gid builder && useradd -m -u $uid -g $gid builder
 ---> Running in d7487a21b414
groupadd: GID '0' already exists
The command '/bin/sh -c groupadd -g $gid builder && useradd -m -u $uid -g $gid builder' returned a non-zero code: 4
*** Error building build image.


```

Do you know what I'm missing?

Kind regards,
Stephan

**Comment by petkivim** [comment]
Hi @DerSIlent 

Did you follow the build instructions described [here](https://github.com/nordic-institute/X-Road/blob/develop/src/BUILD.md)? Before running the `build_packages.sh` script, you must run 1. `prepare_buildhost.sh` and 2. `update_ruby_dependencies.sh`. Those scripts install the required dependencies on the host. Only after running 1 and 2, you should run the `build_packages.sh` script (without `sudo`).

Also, if you don't have local changes in the code base, the easiest way to go is to use the Docker images available on Docker Hub. In that way you don't have to compile the code and build the packages by yourself.

Best regards,
Petteri

**Comment by DerSIlent** [comment]
Hello @petkivim

I will try out the hub docker images soon.

After following the native steps (before I tried the docker option) it crashed at 99% during the `build_packages.sh` :(.

```

> Task :proxy:runProxyTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':proxy:runProxyTest'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 137

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
* org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':proxy:runProxyTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)


```

**Comment by petkivim** [comment]
Hi @DerSIlent 

How much memory you have allocated for the VM where you're running the build? The exit value `137` seems to indicate that memory is running short. The recommendation is to have at least 8GB of memory and 20GB of free disk space.

The easiest way to go is to use the Docker images. In that way you don't need to run the build. [This](https://hub.docker.com/r/niis/xroad-security-server-sidecar) Security Server Docker image is for production. However, the [Central Server image](https://hub.docker.com/r/niis/xroad-central-server) is for test and development purposes only.

Best regards,
Petteri

**Comment by DerSIlent** [comment]
Hello @petkivim 

I never considered googling that error code, thanks!

Using 8GBs of RAM did the trick. I thought I could get away with using 4GBs. I should be able to continue on from this point, so thanks again!

I must ask, is there any difference between the native and docker build for xroad? And the images are just the standalone server?

Kind regards,
Stephan Ruiz

**Comment by petkivim** [comment]
Hi @DerSIlent 

There's no difference between the packages created by the native build and Docker build. The packages are for a regular X-Road installation. However, the Docker build creates both .deb and .rpm packages while the native build creates .deb packages only.

Best regards,
Petteri

**Comment by DerSIlent** [comment]
Hello @petkivim 

Thank you!

Kind regards,
Stephan
