### ISSUE TITLE
Ubuntu Installation fails

### ISSUE THREAD

**Issue by jpadrianoGo** [nordic-institute/X-Road#932]
What has been done:
1. Fresh EC-2 instance Ubuntu Version 20.04
2. Installation of docker Docker version 20.10.5, build 55c4c88
3. git clone https://github.com/nordic-institute/X-Road.git (develop branch)
4. cd X-Road/src
5. sudo ./build_packages.sh -d
Output:
Building in docker...
Sending build context to Docker daemon  3.584kB
Step 1/18 : FROM ubuntu:18.04
 ---> 3339fde08fc3
Step 2/18 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 9aae930778ab
Step 3/18 : RUN apt-get -qq update   && apt-get -qq upgrade   && apt-get -qq install curl software-properties-common gawk     openjdk-8-jdk-headless build-essential git unzip debhelper   && apt-get -qq autoremove   && apt-get -qq clean
 ---> Using cache
 ---> 6f289e17f21d
Step 4/18 : ARG NODESHASUM=eb89c02153cfa25e40170e5e9b0ab43ad55d456af8b72ad2a8c2a42b7a647432
 ---> Using cache
 ---> 6e9a04da95d0
Step 5/18 : ARG NODEVERSION=v12.21.0
 ---> Using cache
 ---> bb9dcca25331
Step 6/18 : RUN mkdir -p /usr/local/nodejs   && echo "${NODESHASUM}  /tmp/node.tar.xz" >/tmp/shasum   && curl -s -o /tmp/node.tar.xz "https://nodejs.org/dist/$NODEVERSION/node-$NODEVERSION-linux-x64.tar.xz"   && sha256sum -c /tmp/shasum   && tar --strip-components=1 -C /usr/local/nodejs -x -f /tmp/node.tar.xz   && rm -f /tmp/shasum /tmp/node.tar.xz
 ---> Using cache
 ---> 55aaa4065515
Step 7/18 : ARG uid
 ---> Using cache
 ---> 857546ada728
Step 8/18 : ARG gid
 ---> Using cache
 ---> 8f6cec3c0d1f
Step 9/18 : RUN groupadd -g $gid builder && useradd -m -u $uid -g $gid builder
 ---> Running in 1a4ddec4aa40
groupadd: GID '0' already exists
The command '/bin/sh -c groupadd -g $gid builder && useradd -m -u $uid -g $gid builder' returned a non-zero code: 4
*** Error building build image.

**Comment by petkivim** [comment]
Hi @jpadrianoGo 

Have you done some local changes in the X-Road repository? If not and you want to install the official release version of X-Road, the easiest way to do it to use the official release packages. In that case you don't need to compile the code and build the packages by yourself.

Manual installation guides are available here:

* [Security Server](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md)
* [Central Server](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md)

Installation guide with Ansible is available [here](https://github.com/nordic-institute/X-Road/tree/develop/ansible).

Best regards,
Petteri

**Comment by jpadrianoGo** [comment]
Hi Petteri,

Thank you for your response.

I haven't done any local changes but I only wanted to try the official release version of X-Road. Thank you for your support. 

Best Regards
