### ISSUE TITLE
Broken link in guide

### ISSUE THREAD

**Issue by chaimfn** [nordic-institute/X-Road#995]
Hi.

I read this guide of security-server insall/config (https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#314-importing-a-certificate-from-a-security-token), and there is a broken link: 
![sec-server-guide](https://user-images.githubusercontent.com/4123637/122747261-8b0f6700-d293-11eb-9c36-bb7a400363b9.jpg)
![sec-server-guide-broken-link](https://user-images.githubusercontent.com/4123637/122747249-86e34980-d293-11eb-9e81-a39f9225cdfa.jpg)

**Comment by petkivim** [comment]
Hi @chaimfn! Thanks for reporting the issue. It has been fixed now.
